// AUTO-GENERATED by scripts/generate-libs.ts — do not edit.
// Regenerate with `pnpm --filter @voidhash/paywall-build generate:libs`.

import { lib_decorators_d_ts } from "./lib_decorators_d_ts.ts";
import { lib_decorators_legacy_d_ts } from "./lib_decorators_legacy_d_ts.ts";
import { lib_es2015_collection_d_ts } from "./lib_es2015_collection_d_ts.ts";
import { lib_es2015_core_d_ts } from "./lib_es2015_core_d_ts.ts";
import { lib_es2015_d_ts } from "./lib_es2015_d_ts.ts";
import { lib_es2015_generator_d_ts } from "./lib_es2015_generator_d_ts.ts";
import { lib_es2015_iterable_d_ts } from "./lib_es2015_iterable_d_ts.ts";
import { lib_es2015_promise_d_ts } from "./lib_es2015_promise_d_ts.ts";
import { lib_es2015_proxy_d_ts } from "./lib_es2015_proxy_d_ts.ts";
import { lib_es2015_reflect_d_ts } from "./lib_es2015_reflect_d_ts.ts";
import { lib_es2015_symbol_d_ts } from "./lib_es2015_symbol_d_ts.ts";
import { lib_es2015_symbol_wellknown_d_ts } from "./lib_es2015_symbol_wellknown_d_ts.ts";
import { lib_es2016_array_include_d_ts } from "./lib_es2016_array_include_d_ts.ts";
import { lib_es2016_d_ts } from "./lib_es2016_d_ts.ts";
import { lib_es2016_intl_d_ts } from "./lib_es2016_intl_d_ts.ts";
import { lib_es2017_arraybuffer_d_ts } from "./lib_es2017_arraybuffer_d_ts.ts";
import { lib_es2017_d_ts } from "./lib_es2017_d_ts.ts";
import { lib_es2017_date_d_ts } from "./lib_es2017_date_d_ts.ts";
import { lib_es2017_intl_d_ts } from "./lib_es2017_intl_d_ts.ts";
import { lib_es2017_object_d_ts } from "./lib_es2017_object_d_ts.ts";
import { lib_es2017_sharedmemory_d_ts } from "./lib_es2017_sharedmemory_d_ts.ts";
import { lib_es2017_string_d_ts } from "./lib_es2017_string_d_ts.ts";
import { lib_es2017_typedarrays_d_ts } from "./lib_es2017_typedarrays_d_ts.ts";
import { lib_es2018_asyncgenerator_d_ts } from "./lib_es2018_asyncgenerator_d_ts.ts";
import { lib_es2018_asynciterable_d_ts } from "./lib_es2018_asynciterable_d_ts.ts";
import { lib_es2018_d_ts } from "./lib_es2018_d_ts.ts";
import { lib_es2018_intl_d_ts } from "./lib_es2018_intl_d_ts.ts";
import { lib_es2018_promise_d_ts } from "./lib_es2018_promise_d_ts.ts";
import { lib_es2018_regexp_d_ts } from "./lib_es2018_regexp_d_ts.ts";
import { lib_es2019_array_d_ts } from "./lib_es2019_array_d_ts.ts";
import { lib_es2019_d_ts } from "./lib_es2019_d_ts.ts";
import { lib_es2019_intl_d_ts } from "./lib_es2019_intl_d_ts.ts";
import { lib_es2019_object_d_ts } from "./lib_es2019_object_d_ts.ts";
import { lib_es2019_string_d_ts } from "./lib_es2019_string_d_ts.ts";
import { lib_es2019_symbol_d_ts } from "./lib_es2019_symbol_d_ts.ts";
import { lib_es2020_bigint_d_ts } from "./lib_es2020_bigint_d_ts.ts";
import { lib_es2020_d_ts } from "./lib_es2020_d_ts.ts";
import { lib_es2020_date_d_ts } from "./lib_es2020_date_d_ts.ts";
import { lib_es2020_intl_d_ts } from "./lib_es2020_intl_d_ts.ts";
import { lib_es2020_number_d_ts } from "./lib_es2020_number_d_ts.ts";
import { lib_es2020_promise_d_ts } from "./lib_es2020_promise_d_ts.ts";
import { lib_es2020_sharedmemory_d_ts } from "./lib_es2020_sharedmemory_d_ts.ts";
import { lib_es2020_string_d_ts } from "./lib_es2020_string_d_ts.ts";
import { lib_es2020_symbol_wellknown_d_ts } from "./lib_es2020_symbol_wellknown_d_ts.ts";
import { lib_es2021_d_ts } from "./lib_es2021_d_ts.ts";
import { lib_es2021_intl_d_ts } from "./lib_es2021_intl_d_ts.ts";
import { lib_es2021_promise_d_ts } from "./lib_es2021_promise_d_ts.ts";
import { lib_es2021_string_d_ts } from "./lib_es2021_string_d_ts.ts";
import { lib_es2021_weakref_d_ts } from "./lib_es2021_weakref_d_ts.ts";
import { lib_es2022_array_d_ts } from "./lib_es2022_array_d_ts.ts";
import { lib_es2022_d_ts } from "./lib_es2022_d_ts.ts";
import { lib_es2022_error_d_ts } from "./lib_es2022_error_d_ts.ts";
import { lib_es2022_intl_d_ts } from "./lib_es2022_intl_d_ts.ts";
import { lib_es2022_object_d_ts } from "./lib_es2022_object_d_ts.ts";
import { lib_es2022_regexp_d_ts } from "./lib_es2022_regexp_d_ts.ts";
import { lib_es2022_string_d_ts } from "./lib_es2022_string_d_ts.ts";
import { lib_es5_d_ts } from "./lib_es5_d_ts.ts";

/** Canonical lib file name → d.ts contents. */
export const LIB_ASSETS: Readonly<Record<string, string>> = {
  "lib.decorators.d.ts": lib_decorators_d_ts,
  "lib.decorators.legacy.d.ts": lib_decorators_legacy_d_ts,
  "lib.es2015.collection.d.ts": lib_es2015_collection_d_ts,
  "lib.es2015.core.d.ts": lib_es2015_core_d_ts,
  "lib.es2015.d.ts": lib_es2015_d_ts,
  "lib.es2015.generator.d.ts": lib_es2015_generator_d_ts,
  "lib.es2015.iterable.d.ts": lib_es2015_iterable_d_ts,
  "lib.es2015.promise.d.ts": lib_es2015_promise_d_ts,
  "lib.es2015.proxy.d.ts": lib_es2015_proxy_d_ts,
  "lib.es2015.reflect.d.ts": lib_es2015_reflect_d_ts,
  "lib.es2015.symbol.d.ts": lib_es2015_symbol_d_ts,
  "lib.es2015.symbol.wellknown.d.ts": lib_es2015_symbol_wellknown_d_ts,
  "lib.es2016.array.include.d.ts": lib_es2016_array_include_d_ts,
  "lib.es2016.d.ts": lib_es2016_d_ts,
  "lib.es2016.intl.d.ts": lib_es2016_intl_d_ts,
  "lib.es2017.arraybuffer.d.ts": lib_es2017_arraybuffer_d_ts,
  "lib.es2017.d.ts": lib_es2017_d_ts,
  "lib.es2017.date.d.ts": lib_es2017_date_d_ts,
  "lib.es2017.intl.d.ts": lib_es2017_intl_d_ts,
  "lib.es2017.object.d.ts": lib_es2017_object_d_ts,
  "lib.es2017.sharedmemory.d.ts": lib_es2017_sharedmemory_d_ts,
  "lib.es2017.string.d.ts": lib_es2017_string_d_ts,
  "lib.es2017.typedarrays.d.ts": lib_es2017_typedarrays_d_ts,
  "lib.es2018.asyncgenerator.d.ts": lib_es2018_asyncgenerator_d_ts,
  "lib.es2018.asynciterable.d.ts": lib_es2018_asynciterable_d_ts,
  "lib.es2018.d.ts": lib_es2018_d_ts,
  "lib.es2018.intl.d.ts": lib_es2018_intl_d_ts,
  "lib.es2018.promise.d.ts": lib_es2018_promise_d_ts,
  "lib.es2018.regexp.d.ts": lib_es2018_regexp_d_ts,
  "lib.es2019.array.d.ts": lib_es2019_array_d_ts,
  "lib.es2019.d.ts": lib_es2019_d_ts,
  "lib.es2019.intl.d.ts": lib_es2019_intl_d_ts,
  "lib.es2019.object.d.ts": lib_es2019_object_d_ts,
  "lib.es2019.string.d.ts": lib_es2019_string_d_ts,
  "lib.es2019.symbol.d.ts": lib_es2019_symbol_d_ts,
  "lib.es2020.bigint.d.ts": lib_es2020_bigint_d_ts,
  "lib.es2020.d.ts": lib_es2020_d_ts,
  "lib.es2020.date.d.ts": lib_es2020_date_d_ts,
  "lib.es2020.intl.d.ts": lib_es2020_intl_d_ts,
  "lib.es2020.number.d.ts": lib_es2020_number_d_ts,
  "lib.es2020.promise.d.ts": lib_es2020_promise_d_ts,
  "lib.es2020.sharedmemory.d.ts": lib_es2020_sharedmemory_d_ts,
  "lib.es2020.string.d.ts": lib_es2020_string_d_ts,
  "lib.es2020.symbol.wellknown.d.ts": lib_es2020_symbol_wellknown_d_ts,
  "lib.es2021.d.ts": lib_es2021_d_ts,
  "lib.es2021.intl.d.ts": lib_es2021_intl_d_ts,
  "lib.es2021.promise.d.ts": lib_es2021_promise_d_ts,
  "lib.es2021.string.d.ts": lib_es2021_string_d_ts,
  "lib.es2021.weakref.d.ts": lib_es2021_weakref_d_ts,
  "lib.es2022.array.d.ts": lib_es2022_array_d_ts,
  "lib.es2022.d.ts": lib_es2022_d_ts,
  "lib.es2022.error.d.ts": lib_es2022_error_d_ts,
  "lib.es2022.intl.d.ts": lib_es2022_intl_d_ts,
  "lib.es2022.object.d.ts": lib_es2022_object_d_ts,
  "lib.es2022.regexp.d.ts": lib_es2022_regexp_d_ts,
  "lib.es2022.string.d.ts": lib_es2022_string_d_ts,
  "lib.es5.d.ts": lib_es5_d_ts,
};

/** The default (root) lib the typecheck stage loads. */
export const DEFAULT_LIB = "lib.es2022.d.ts";
