import { constant } from "@voidhash/lib/lang";
import { DateTime, Effect, FileSystem, Layer, Path, Schema, Context } from "effect";

import {
  VOIDHASH_FETCHED_AT_COMMENT_PREFIX,
  VOIDHASH_VERSION_COMMENT_PREFIX,
  parseVersionFromDeclaration,
} from "../../utils/schema/version";
import type { Writable } from "../../utils/types";
import type { NormalizedSchema } from "../schema/normalized-schema";
import type { VoidhashConfigSchema } from "../schema/voidhash-config";

/** Encodes a slug as a quoted TypeScript string literal. */
const toStringLiteral = Schema.encodeSync(Schema.fromJsonString(Schema.String));

function toUnionType(slugs: string[]): string {
  if (slugs.length === 0) {
    return "never";
  }
  return slugs.map((slug) => toStringLiteral(slug)).join(" | ");
}

/**
 * Generate the contents of the `voidhash.gen.d.ts` declaration file.
 *
 * The version baked into the header is supplied by the caller (and ultimately
 * by the server's `GET /api/v1/schema` / `GET /api/v1/schema/version`
 * endpoints) so client and server can never disagree on the hash.
 *
 * The file:
 * - Starts with a `@voidhash:version` header so `voidhash-cli types check` and the
 *   dev-mode runtime warning can detect staleness without re-downloading the
 *   full schema.
 * - Augments `@voidhash/react-native`'s `VoidhashRegister` interface so all
 *   typed hook arguments (slug literals) resolve via the registry.
 */
export function generateTypesDeclaration(
  schema: NormalizedSchema,
  version: string,
  options: { fetchedAt: Date },
): string {
  const fetchedAt = options.fetchedAt.toISOString();

  const productSlugs = [...schema.products.keys()].sort();
  const locationSlugs = [...schema.locations.keys()].sort();
  const perkSlugs = [...schema.perks.keys()].sort();

  const lines: string[] = [];
  lines.push("// voidhash.gen.d.ts — generated by voidhash-cli, do not edit");
  lines.push(`${VOIDHASH_VERSION_COMMENT_PREFIX}${version}`);
  lines.push(`${VOIDHASH_FETCHED_AT_COMMENT_PREFIX}${fetchedAt}`);
  lines.push("");
  lines.push('declare module "@voidhash/react-native" {');
  lines.push("  interface VoidhashRegister {");
  lines.push("    schema: {");
  lines.push(`      products: ${toUnionType(productSlugs)};`);
  lines.push(`      locations: ${toUnionType(locationSlugs)};`);
  lines.push(`      perks: ${toUnionType(perkSlugs)};`);
  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export {};");
  lines.push("");

  return lines.join("\n");
}

const make = Effect.gen(function* effect() {
  const fileSystem = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  /**
   * Scaffold the SDK client module (`voidhash.ts` / `.js`) that wires up
   * `@voidhash/react-native` with the project's publishable key.
   *
   * The key is pre-filled as the default so the file works out of the box;
   * the user is free to edit it and the client options afterwards. The client
   * is exported as a single `voidhash` object, so the rest of the app uses it
   * like `<voidhash.Provider>` or `voidhash.useProducts()`. The parent
   * directory (`src/lib` or `lib`) is created if it does not exist yet.
   */
  const generateClientFile = (filePath: string, options: { publishableKey: string }) =>
    Effect.gen(function* generateClientFile() {
      yield* fileSystem.makeDirectory(path.dirname(filePath), {
        recursive: true,
      });
      const lines = [
        'import { createVoidhashClient } from "@voidhash/react-native";',
        "",
        "/**",
        " * Voidhash SDK client. Safe to edit.",
        " *",
        " * Use it like `<voidhash.Provider>` and `voidhash.useProducts()`. The",
        " * publishable key is safe to ship in client code.",
        " */",
        `export const voidhash = createVoidhashClient("${options.publishableKey}", { dev: true });`,
        "",
      ];
      yield* fileSystem.writeFileString(filePath, lines.join("\n"));
    });

  const generateVoidhashConfigFile = (
    filePath: string,
    config: Writable<typeof VoidhashConfigSchema.Type>,
  ) =>
    Effect.gen(function* generateVoidhashConfigFile() {
      const lines = [
        "import { defineConfig } from 'voidhash-cli';",
        "",
        "export default defineConfig({",
        `  team: '${config.team}',`,
        `  project: '${config.project}',`,
      ];
      if (config.typesOutput !== undefined) {
        lines.push(`  typesOutput: '${config.typesOutput}',`);
      }
      lines.push("});", "");
      yield* fileSystem.writeFileString(filePath, lines.join("\n"));
    });

  /**
   * Generate the `.d.ts` declaration file from the remote schema and write it
   * to disk. `version` is the server-provided hash that gets baked into the
   * header so the CI gate / dev-mode warning can detect drift.
   */
  const generateTypesDeclarationFile = (
    filePath: string,
    schema: NormalizedSchema,
    version: string,
  ) =>
    Effect.gen(function* generateTypesDeclarationFile() {
      const fetchedAt = yield* DateTime.nowAsDate;
      const content = generateTypesDeclaration(schema, version, { fetchedAt });
      yield* fileSystem.writeFileString(filePath, content);
      return version;
    });

  const readDeclarationVersion = (filePath: string) =>
    Effect.gen(function* readDeclarationVersion() {
      const content = yield* fileSystem.readFileString(filePath);
      return parseVersionFromDeclaration(content);
    });

  return constant({
    generateClientFile,
    generateTypesDeclarationFile,
    generateVoidhashConfigFile,
    readDeclarationVersion,
  });
});

type CodegenShape = Effect.Success<typeof make>;

export class Codegen extends Context.Service<Codegen, CodegenShape>()("voidhash-cli/Codegen") {
  static Default = Layer.effect(Codegen, make);
}
