/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AppRouteRouteImport } from "./routes/_app/route";
import { Route as AppLayoutRouteRouteImport } from "./routes/_app/_layout/route";
import { Route as AppLayoutIndexRouteImport } from "./routes/_app/_layout/index";
import { Route as AppLayoutMigrationsRouteImport } from "./routes/_app/_layout/migrations";
import { Route as AppLayoutUsersRouteImport } from "./routes/_app/_layout/users";
import { Route as AppLayoutObservabilityRouteImport } from "./routes/_app/_layout/observability";
import { Route as AppLayoutDatabasesRouteImport } from "./routes/_app/_layout/databases";
import { Route as AppLayoutCollectionsCollectionIdIndexRouteImport } from "./routes/_app/_layout/collections/$collectionId/index";
import { Route as AppLayoutCollectionsCollectionIdSchemaRouteImport } from "./routes/_app/_layout/collections/$collectionId/schema";
import { Route as AppLayoutCollectionsCollectionIdDocumentsDocumentIdRouteImport } from "./routes/_app/_layout/collections/$collectionId/documents/$documentId";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const AppLayoutRouteRoute = AppLayoutRouteRouteImport.update({
  id: "/_layout",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppLayoutRouteRoute,
} as any);
const AppLayoutMigrationsRoute = AppLayoutMigrationsRouteImport.update({
  id: "/migrations",
  path: "/migrations",
  getParentRoute: () => AppLayoutRouteRoute,
} as any);
const AppLayoutUsersRoute = AppLayoutUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AppLayoutRouteRoute,
} as any);
const AppLayoutObservabilityRoute = AppLayoutObservabilityRouteImport.update({
  id: "/observability",
  path: "/observability",
  getParentRoute: () => AppLayoutRouteRoute,
} as any);
const AppLayoutDatabasesRoute = AppLayoutDatabasesRouteImport.update({
  id: "/databases",
  path: "/databases",
  getParentRoute: () => AppLayoutRouteRoute,
} as any);
const AppLayoutCollectionsCollectionIdIndexRoute =
  AppLayoutCollectionsCollectionIdIndexRouteImport.update({
    id: "/collections/$collectionId/",
    path: "/collections/$collectionId/",
    getParentRoute: () => AppLayoutRouteRoute,
  } as any);
const AppLayoutCollectionsCollectionIdSchemaRoute =
  AppLayoutCollectionsCollectionIdSchemaRouteImport.update({
    id: "/collections/$collectionId/schema",
    path: "/collections/$collectionId/schema",
    getParentRoute: () => AppLayoutRouteRoute,
  } as any);
const AppLayoutCollectionsCollectionIdDocumentsDocumentIdRoute =
  AppLayoutCollectionsCollectionIdDocumentsDocumentIdRouteImport.update({
    id: "/collections/$collectionId/documents/$documentId",
    path: "/collections/$collectionId/documents/$documentId",
    getParentRoute: () => AppLayoutRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AppLayoutIndexRoute;
  "/login": typeof LoginRoute;
  "/databases": typeof AppLayoutDatabasesRoute;
  "/migrations": typeof AppLayoutMigrationsRoute;
  "/observability": typeof AppLayoutObservabilityRoute;
  "/users": typeof AppLayoutUsersRoute;
  "/collections/$collectionId/schema": typeof AppLayoutCollectionsCollectionIdSchemaRoute;
  "/collections/$collectionId/": typeof AppLayoutCollectionsCollectionIdIndexRoute;
  "/collections/$collectionId/documents/$documentId": typeof AppLayoutCollectionsCollectionIdDocumentsDocumentIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof AppLayoutIndexRoute;
  "/login": typeof LoginRoute;
  "/databases": typeof AppLayoutDatabasesRoute;
  "/migrations": typeof AppLayoutMigrationsRoute;
  "/observability": typeof AppLayoutObservabilityRoute;
  "/users": typeof AppLayoutUsersRoute;
  "/collections/$collectionId/schema": typeof AppLayoutCollectionsCollectionIdSchemaRoute;
  "/collections/$collectionId": typeof AppLayoutCollectionsCollectionIdIndexRoute;
  "/collections/$collectionId/documents/$documentId": typeof AppLayoutCollectionsCollectionIdDocumentsDocumentIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_app/_layout": typeof AppLayoutRouteRouteWithChildren;
  "/_app/_layout/databases": typeof AppLayoutDatabasesRoute;
  "/_app/_layout/migrations": typeof AppLayoutMigrationsRoute;
  "/_app/_layout/observability": typeof AppLayoutObservabilityRoute;
  "/_app/_layout/users": typeof AppLayoutUsersRoute;
  "/_app/_layout/": typeof AppLayoutIndexRoute;
  "/_app/_layout/collections/$collectionId/schema": typeof AppLayoutCollectionsCollectionIdSchemaRoute;
  "/_app/_layout/collections/$collectionId/": typeof AppLayoutCollectionsCollectionIdIndexRoute;
  "/_app/_layout/collections/$collectionId/documents/$documentId": typeof AppLayoutCollectionsCollectionIdDocumentsDocumentIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/databases"
    | "/migrations"
    | "/observability"
    | "/users"
    | "/collections/$collectionId/schema"
    | "/collections/$collectionId/"
    | "/collections/$collectionId/documents/$documentId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/databases"
    | "/migrations"
    | "/observability"
    | "/users"
    | "/collections/$collectionId/schema"
    | "/collections/$collectionId"
    | "/collections/$collectionId/documents/$documentId";
  id:
    | "__root__"
    | "/_app"
    | "/login"
    | "/_app/_layout"
    | "/_app/_layout/databases"
    | "/_app/_layout/migrations"
    | "/_app/_layout/observability"
    | "/_app/_layout/users"
    | "/_app/_layout/"
    | "/_app/_layout/collections/$collectionId/schema"
    | "/_app/_layout/collections/$collectionId/"
    | "/_app/_layout/collections/$collectionId/documents/$documentId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/_layout": {
      id: "/_app/_layout";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppLayoutRouteRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/_layout/": {
      id: "/_app/_layout/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppLayoutIndexRouteImport;
      parentRoute: typeof AppLayoutRouteRoute;
    };
    "/_app/_layout/users": {
      id: "/_app/_layout/users";
      path: "/users";
      fullPath: "/users";
      preLoaderRoute: typeof AppLayoutUsersRouteImport;
      parentRoute: typeof AppLayoutRouteRoute;
    };
    "/_app/_layout/migrations": {
      id: "/_app/_layout/migrations";
      path: "/migrations";
      fullPath: "/migrations";
      preLoaderRoute: typeof AppLayoutMigrationsRouteImport;
      parentRoute: typeof AppLayoutRouteRoute;
    };
    "/_app/_layout/observability": {
      id: "/_app/_layout/observability";
      path: "/observability";
      fullPath: "/observability";
      preLoaderRoute: typeof AppLayoutObservabilityRouteImport;
      parentRoute: typeof AppLayoutRouteRoute;
    };
    "/_app/_layout/databases": {
      id: "/_app/_layout/databases";
      path: "/databases";
      fullPath: "/databases";
      preLoaderRoute: typeof AppLayoutDatabasesRouteImport;
      parentRoute: typeof AppLayoutRouteRoute;
    };
    "/_app/_layout/collections/$collectionId/": {
      id: "/_app/_layout/collections/$collectionId/";
      path: "/collections/$collectionId";
      fullPath: "/collections/$collectionId/";
      preLoaderRoute: typeof AppLayoutCollectionsCollectionIdIndexRouteImport;
      parentRoute: typeof AppLayoutRouteRoute;
    };
    "/_app/_layout/collections/$collectionId/schema": {
      id: "/_app/_layout/collections/$collectionId/schema";
      path: "/collections/$collectionId/schema";
      fullPath: "/collections/$collectionId/schema";
      preLoaderRoute: typeof AppLayoutCollectionsCollectionIdSchemaRouteImport;
      parentRoute: typeof AppLayoutRouteRoute;
    };
    "/_app/_layout/collections/$collectionId/documents/$documentId": {
      id: "/_app/_layout/collections/$collectionId/documents/$documentId";
      path: "/collections/$collectionId/documents/$documentId";
      fullPath: "/collections/$collectionId/documents/$documentId";
      preLoaderRoute: typeof AppLayoutCollectionsCollectionIdDocumentsDocumentIdRouteImport;
      parentRoute: typeof AppLayoutRouteRoute;
    };
  }
}

interface AppLayoutRouteRouteChildren {
  AppLayoutDatabasesRoute: typeof AppLayoutDatabasesRoute;
  AppLayoutMigrationsRoute: typeof AppLayoutMigrationsRoute;
  AppLayoutObservabilityRoute: typeof AppLayoutObservabilityRoute;
  AppLayoutUsersRoute: typeof AppLayoutUsersRoute;
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute;
  AppLayoutCollectionsCollectionIdSchemaRoute: typeof AppLayoutCollectionsCollectionIdSchemaRoute;
  AppLayoutCollectionsCollectionIdIndexRoute: typeof AppLayoutCollectionsCollectionIdIndexRoute;
  AppLayoutCollectionsCollectionIdDocumentsDocumentIdRoute: typeof AppLayoutCollectionsCollectionIdDocumentsDocumentIdRoute;
}

const AppLayoutRouteRouteChildren: AppLayoutRouteRouteChildren = {
  AppLayoutDatabasesRoute: AppLayoutDatabasesRoute,
  AppLayoutMigrationsRoute: AppLayoutMigrationsRoute,
  AppLayoutObservabilityRoute: AppLayoutObservabilityRoute,
  AppLayoutUsersRoute: AppLayoutUsersRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutCollectionsCollectionIdSchemaRoute: AppLayoutCollectionsCollectionIdSchemaRoute,
  AppLayoutCollectionsCollectionIdIndexRoute: AppLayoutCollectionsCollectionIdIndexRoute,
  AppLayoutCollectionsCollectionIdDocumentsDocumentIdRoute:
    AppLayoutCollectionsCollectionIdDocumentsDocumentIdRoute,
};

const AppLayoutRouteRouteWithChildren = AppLayoutRouteRoute._addFileChildren(
  AppLayoutRouteRouteChildren,
);

interface AppRouteRouteChildren {
  AppLayoutRouteRoute: typeof AppLayoutRouteRouteWithChildren;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppLayoutRouteRoute: AppLayoutRouteRouteWithChildren,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(AppRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
