import { describe, expect, it } from "vitest";

import { NODE_STYLE_VOCABULARY, type CompositionNodeType } from "../src/compose/index";
import { PAYWALL_STYLE_KEY_LIST } from "../src/schema/index";

/**
 * Equivalence lock for the single-sourced style vocabulary.
 *
 * Both tables (`PAYWALL_STYLE_KEY_LIST` — the wire contract — and
 * `NODE_STYLE_VOCABULARY` — the printer-significant per-node compose grammar)
 * are now derived from one style-field registry (`src/schema/style-registry.ts`).
 * This test hardcodes their EXACT pre-refactor values so the derivation is
 * provably output-identical: field order and every default value are locked, as
 * is the content and order of the wire key list. A drift in either derivation
 * fails here.
 */

const EXPECTED_STYLE_KEY_LIST = [
  "flex",
  "flexDirection",
  "alignItems",
  "alignSelf",
  "justifyContent",
  "flexWrap",
  "gap",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "width",
  "height",
  "minWidth",
  "minHeight",
  "maxWidth",
  "maxHeight",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "aspectRatio",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "borderColor",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderStyle",
  "backgroundColor",
  "backgroundType",
  "backgroundGradient",
  "backgroundImage",
  "opacity",
  "overflow",
  "position",
  "top",
  "right",
  "bottom",
  "left",
  "zIndex",
  "color",
  "fontSize",
  "fontWeight",
  "fontStyle",
  "lineHeight",
  "letterSpacing",
  "textAlign",
  "textTransform",
  "textDecorationLine",
  "fontFamily",
];

const CANONICAL_GRADIENT = {
  kind: "linear",
  startX: 0.5,
  startY: 0,
  endX: 0.5,
  endY: 1,
  stops: [
    { color: "rgba(255, 255, 255, 1)", position: 0 },
    { color: "rgba(255, 255, 255, 0)", position: 1 },
  ],
};

const EXPECTED_SCREEN = {
  styleFields: [
    "x",
    "y",
    "width",
    "height",
    "minWidth",
    "maxWidth",
    "minHeight",
    "maxHeight",
    "paddingTop",
    "paddingRight",
    "paddingBottom",
    "paddingLeft",
    "marginTop",
    "marginRight",
    "marginBottom",
    "marginLeft",
    "gap",
    "justifyContent",
    "alignItems",
    "flexDirection",
    "backgroundColor",
    "backgroundEnabled",
    "backgroundType",
    "backgroundGradient",
    "backgroundImage",
    "borderTopWidth",
    "borderRightWidth",
    "borderBottomWidth",
    "borderLeftWidth",
    "borderColor",
    "borderStyle",
    "borderEnabled",
    "opacity",
    "overflow",
    "zIndex",
    "display",
    "shadowEnabled",
    "shadowColor",
    "shadowOffsetX",
    "shadowOffsetY",
    "shadowRadius",
    "shadowOpacity",
    "safeAreaTop",
    "safeAreaBottom",
    "flex",
    "flexGrow",
    "flexShrink",
    "flexBasis",
    "alignSelf",
  ],
  defaultStyle: {
    x: 0,
    y: 0,
    width: 375,
    height: 812,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    gap: 0,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    flexDirection: "column",
    backgroundColor: "rgba(255, 255, 255, 1)",
    backgroundEnabled: true,
    backgroundType: "solid",
    backgroundGradient: CANONICAL_GRADIENT,
    backgroundImage: { url: "", resizeMode: "cover" },
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderColor: "rgba(0, 0, 0, 1)",
    borderStyle: "solid",
    borderEnabled: false,
    opacity: 1,
    overflow: "visible",
    zIndex: 0,
    display: "flex",
    shadowEnabled: false,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowRadius: 0,
    shadowOpacity: 1,
    safeAreaTop: false,
    safeAreaBottom: false,
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    alignSelf: "auto",
  },
  defaultName: "Screen",
};

const EXPECTED_VIEW = {
  styleFields: [
    "paddingTop",
    "paddingRight",
    "paddingBottom",
    "paddingLeft",
    "marginTop",
    "marginRight",
    "marginBottom",
    "marginLeft",
    "gap",
    "justifyContent",
    "alignItems",
    "flexDirection",
    "width",
    "height",
    "minWidth",
    "maxWidth",
    "minHeight",
    "maxHeight",
    "backgroundColor",
    "backgroundEnabled",
    "backgroundType",
    "backgroundGradient",
    "backgroundImage",
    "borderTopWidth",
    "borderRightWidth",
    "borderBottomWidth",
    "borderLeftWidth",
    "borderColor",
    "borderStyle",
    "borderEnabled",
    "borderTopLeftRadius",
    "borderTopRightRadius",
    "borderBottomRightRadius",
    "borderBottomLeftRadius",
    "opacity",
    "overflow",
    "zIndex",
    "position",
    "left",
    "top",
    "right",
    "bottom",
    "display",
    "shadowEnabled",
    "shadowColor",
    "shadowOffsetX",
    "shadowOffsetY",
    "shadowRadius",
    "shadowOpacity",
    "safeAreaTop",
    "safeAreaBottom",
    "flex",
    "flexGrow",
    "flexShrink",
    "flexBasis",
    "alignSelf",
  ],
  defaultStyle: {
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    gap: 0,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    flexDirection: "column",
    width: 100,
    height: 100,
    backgroundColor: "rgba(255, 255, 255, 1)",
    backgroundEnabled: false,
    backgroundType: "solid",
    backgroundGradient: CANONICAL_GRADIENT,
    backgroundImage: { url: "", resizeMode: "cover" },
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderColor: "rgba(0, 0, 0, 1)",
    borderStyle: "solid",
    borderEnabled: false,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
    opacity: 1,
    overflow: "visible",
    zIndex: 0,
    position: "relative",
    left: "auto",
    top: "auto",
    right: "auto",
    bottom: "auto",
    display: "flex",
    shadowEnabled: false,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowRadius: 0,
    shadowOpacity: 1,
    safeAreaTop: false,
    safeAreaBottom: false,
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    alignSelf: "auto",
  },
  defaultName: "View",
};

const EXPECTED_TEXT = {
  styleFields: [
    "marginTop",
    "marginRight",
    "marginBottom",
    "marginLeft",
    "minWidth",
    "maxWidth",
    "minHeight",
    "maxHeight",
    "fontSize",
    "fontWeight",
    "color",
    "textAlign",
    "lineHeight",
    "letterSpacing",
    "borderTopWidth",
    "borderRightWidth",
    "borderBottomWidth",
    "borderLeftWidth",
    "borderColor",
    "borderStyle",
    "borderEnabled",
    "opacity",
    "overflow",
    "zIndex",
    "position",
    "left",
    "top",
    "right",
    "bottom",
    "display",
    "shadowEnabled",
    "shadowColor",
    "shadowOffsetX",
    "shadowOffsetY",
    "shadowRadius",
    "shadowOpacity",
    "flex",
    "flexGrow",
    "flexShrink",
    "flexBasis",
    "alignSelf",
  ],
  defaultStyle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    fontSize: 16,
    fontWeight: "400",
    color: "rgba(0, 0, 0, 1)",
    textAlign: "left",
    lineHeight: 1.5,
    letterSpacing: 0,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderColor: "rgba(0, 0, 0, 1)",
    borderStyle: "solid",
    borderEnabled: false,
    opacity: 1,
    overflow: "visible",
    zIndex: 0,
    position: "relative",
    left: "auto",
    top: "auto",
    right: "auto",
    bottom: "auto",
    display: "flex",
    shadowEnabled: false,
    shadowColor: "rgba(0, 0, 0, 1)",
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowRadius: 0,
    shadowOpacity: 1,
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    alignSelf: "auto",
  },
  defaultName: "Text",
};

interface ExpectedNodeVocabulary {
  styleFields: string[];
  defaultStyle: Record<string, unknown>;
  defaultName: string;
}

const EXPECTED_VOCABULARY: Record<CompositionNodeType, ExpectedNodeVocabulary> = {
  screen: EXPECTED_SCREEN,
  view: EXPECTED_VIEW,
  text: EXPECTED_TEXT,
};

describe("PAYWALL_STYLE_KEY_LIST (wire contract lock)", () => {
  it("matches the locked content AND order exactly", () => {
    expect([...PAYWALL_STYLE_KEY_LIST]).toEqual(EXPECTED_STYLE_KEY_LIST);
  });
});

describe("NODE_STYLE_VOCABULARY (compose grammar lock)", () => {
  for (const type of ["screen", "view", "text"] as const) {
    describe(type, () => {
      it("preserves the printer-significant styleFields order", () => {
        expect([...NODE_STYLE_VOCABULARY[type].styleFields]).toEqual(
          EXPECTED_VOCABULARY[type].styleFields,
        );
      });

      it("preserves every default value (and the exact default key set)", () => {
        expect(NODE_STYLE_VOCABULARY[type].defaultStyle).toEqual(
          EXPECTED_VOCABULARY[type].defaultStyle,
        );
        expect(Object.keys(NODE_STYLE_VOCABULARY[type].defaultStyle)).toEqual(
          Object.keys(EXPECTED_VOCABULARY[type].defaultStyle),
        );
      });

      it("preserves the default node name", () => {
        expect(NODE_STYLE_VOCABULARY[type].defaultName).toBe(EXPECTED_VOCABULARY[type].defaultName);
      });
    });
  }
});
