packages:
  - packages/*
  - apps/*
  - libraries/*
  - examples/*
catalog:
  "@types/react": ^18.3.14
  "@types/react-dom": ^18.3.2
  "@trpc/client": ^11.1.0
  "@trpc/server": ^11.1.0
  "@tanstack/react-query": ^5.90.5
  "@trpc/tanstack-react-query": ^11.1.0
  "effect": "^3.18.4"
  "@effect/platform-node": "^0.100.0"
  "@effect/platform-bun": "^0.83.0"
  "@effect/platform": "^0.93.0"
  "@effect/cluster": "^0.52.9"
  "@effect/cli": "^0.72.1"
  "@effect/rpc": "^0.72.1"
  "@effect/language-service": "^0.55.3"
  "@effect/vitest": "^0.27.0"
  superjson: ^2.2.2
catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - msgpackr-extract
  - msw
  - nitro-codegen
  - protobufjs
  - react-native-nitro-modules
  - sharp
  - simple-git-hooks
  - unrs-resolver
