import { HttpApi, HttpApiEndpoint, HttpApiGroup } from "@effect/platform";
import { Schema } from "effect";

import {
  ActionForbiddenError,
  ApiKeyNotFoundError,
  ApiKeyServiceError,
  AuthenticationError,
  ChangesetDeploymentServiceError,
  CustomerInvalidAnonymousIdError,
  CustomerNotFoundError,
  CustomerServiceError,
  OrganizationServiceError,
  PaymentProviderConfigurationServiceError,
  PaymentProviderProductServiceError,
  PaywallNotFoundError,
  PaywallLocationServiceError,
  PaywallServiceError,
  PaywallSlugAlreadyExistsError,
  PerkServiceError,
  ProductPerkServiceError,
  ProductPerkValidationError,
  ProductServiceError,
  ProjectServiceError,
  SdkCustomerAlreadyIdentifiedError,
  SdkCustomerNotFoundError,
  SdkServiceError,
  SdkValidationError,
  UserServiceError,
  WebhookDeliveryNotFoundError,
  WebhookEndpointNotFoundError,
  WebhookServiceError,
  WebhookValidationError,
} from "./errors";
import { AuthMiddleware } from "./middlewares";
import {
  ApiKey,
  ApiKeyIdParam,
  ApiKeyWithRawKey,
  AppUserIdParam,
  CreateCustomerBody,
  CreateOrganizationBody,
  CreateProjectBody,
  CreateSecretKeyBody,
  CreateWebhookEndpointBody,
  Customer,
  CustomerIdParam,
  CreatePaywallBody,
  DeployChangesetBody,
  DeployChangesetResponse,
  Organization,
  OrganizationIdParam,
  PaymentProviderConfiguration,
  PaymentProviderProduct,
  Paywall,
  PaywallEditToken,
  PaywallIdParam,
  PaywallLocation,
  Perk,
  Product,
  ProductIdParam,
  ProductPerk,
  ProjectIdParam,
  Project,
  EvaluateFeatureFlagsBody,
  SdkCustomer,
  SdkFeatureFlagsResponse,
  SdkHeaders,
  SdkIdentifyBody,
  SdkResolvePaywallBody,
  SdkResolvedPaywall,
  SdkSyncCustomerAttributesBody,
  SdkSyncTransactionBody,
  SdkSyncTransactionResponse,
  Session,
  UpdateWebhookEndpointBody,
  User,
  WebhookDelivery,
  WebhookDeliveryIdParam,
  WebhookDeliveryWithAttempts,
  WebhookEndpoint,
  WebhookEndpointIdParam,
} from "./schema";

export const VoidhashV1Api = HttpApi.make("VoidhashV1Api")
  .add(
    HttpApiGroup.make("auth")
      .add(
        HttpApiEndpoint.get("session")`/session`
          .addSuccess(Session)
          .addError(ActionForbiddenError)
          .middleware(AuthMiddleware)
      )
      .prefix("/auth")
  )
  .add(
    HttpApiGroup.make("api_keys")
      .add(
        HttpApiEndpoint.post("createSecretKey")`/`
          .addSuccess(ApiKeyWithRawKey)
          .setPayload(CreateSecretKeyBody)
          .addError(ApiKeyServiceError)
          .addError(ActionForbiddenError)
      )
      .add(
        HttpApiEndpoint.get("listApiKeys")`/`
          .addSuccess(Schema.Array(ApiKey))
          .addError(ApiKeyServiceError)
          .addError(ActionForbiddenError)
      )
      .add(
        HttpApiEndpoint.get("getApiKeyById")`/${ApiKeyIdParam}`
          .addSuccess(ApiKey)
          .addError(ApiKeyServiceError)
          .addError(ApiKeyNotFoundError)
          .addError(ActionForbiddenError)
      )
      .add(
        HttpApiEndpoint.post("rotateSecretKey")`/${ApiKeyIdParam}/rotate`
          .addSuccess(ApiKeyWithRawKey)
          .addError(ApiKeyServiceError)
          .addError(ApiKeyNotFoundError)
          .addError(ActionForbiddenError)
      )
      .add(
        HttpApiEndpoint.del("deleteApiKey")`/${ApiKeyIdParam}`
          .addError(ApiKeyServiceError)
          .addError(ApiKeyNotFoundError)
          .addError(ActionForbiddenError)
      )
      .middleware(AuthMiddleware)
      .prefix("/api-keys")
  )
  .add(
    HttpApiGroup.make("customers")
      .add(
        HttpApiEndpoint.post("createCustomer")`/`
          .setPayload(CreateCustomerBody)
          .addSuccess(Customer)
          .addError(ActionForbiddenError)
          .addError(CustomerInvalidAnonymousIdError)
          .addError(CustomerServiceError)
      )
      .add(
        HttpApiEndpoint.get("listCustomers")`/`
          .addSuccess(Schema.Array(Customer))
          .addError(ActionForbiddenError)
          .addError(CustomerServiceError)
      )
      .add(
        HttpApiEndpoint.get("getCustomerById")`/${CustomerIdParam}`
          .addSuccess(Customer)
          .addError(ActionForbiddenError)
          .addError(CustomerNotFoundError)
          .addError(CustomerServiceError)
      )
      .add(
        HttpApiEndpoint.get("byAppUserId")`/by-app-user-id/${AppUserIdParam}`
          .addSuccess(Customer)
          .addError(ActionForbiddenError)
          .addError(CustomerNotFoundError)
          .addError(CustomerServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/customers")
  )
  .add(
    HttpApiGroup.make("organizations")
      .add(
        HttpApiEndpoint.post("createOrganization")`/`
          .setPayload(CreateOrganizationBody)
          .addSuccess(Organization)
          .addError(OrganizationServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/organizations")
  )
  .add(
    HttpApiGroup.make("perks")
      .add(
        HttpApiEndpoint.get("listPerks")`/`
          .addSuccess(Schema.Array(Perk))
          .addError(ActionForbiddenError)
          .addError(PerkServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/perks")
  )
  .add(
    HttpApiGroup.make("paywall_locations")
      .add(
        HttpApiEndpoint.get("listPaywallLocations")`/`
          .addSuccess(Schema.Array(PaywallLocation))
          .addError(ActionForbiddenError)
          .addError(PaywallLocationServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/paywall-locations")
  )
  .add(
    HttpApiGroup.make("paywalls")
      .add(
        HttpApiEndpoint.get("listPaywallsByProjectId")`/by-project-id/${ProjectIdParam}`
          .addSuccess(Schema.Array(Paywall))
          .addError(ActionForbiddenError)
          .addError(PaywallServiceError)
      )
      .add(
        HttpApiEndpoint.post("createPaywall")`/`
          .setPayload(CreatePaywallBody)
          .addSuccess(Schema.Struct({ id: Schema.String }))
          .addError(ActionForbiddenError)
          .addError(PaywallServiceError)
          .addError(PaywallSlugAlreadyExistsError)
      )
      .add(
        HttpApiEndpoint.post("requestPaywallEditToken")`/${PaywallIdParam}/edit-token`
          .addSuccess(PaywallEditToken)
          .addError(ActionForbiddenError)
          .addError(PaywallServiceError)
          .addError(PaywallNotFoundError)
      )
      .middleware(AuthMiddleware)
      .prefix("/paywalls")
  )
  .add(
    HttpApiGroup.make("projects")
      .add(
        HttpApiEndpoint.post("createProject")`/`
          .setPayload(CreateProjectBody)
          .addSuccess(Project)
          .addError(ActionForbiddenError)
          .addError(AuthenticationError)
          .addError(ProjectServiceError)
      )
      .add(
        HttpApiEndpoint.get("listProjects")`/${OrganizationIdParam}`
          .addSuccess(Schema.Array(Project))
          .addError(ActionForbiddenError)
          .addError(ProjectServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/projects")
  )
  .add(
    HttpApiGroup.make("products")
      .add(
        HttpApiEndpoint.get("listProducts")`/`
          .addSuccess(Schema.Array(Product))
          .addError(ActionForbiddenError)
          .addError(ProductServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/products")
  )
  .add(
    HttpApiGroup.make("product_perks")
      .add(
        HttpApiEndpoint.get(
          "listProductPerksByProductId"
        )`/by-product-id/${ProductIdParam}`
          .addSuccess(Schema.Array(ProductPerk))
          .addError(ActionForbiddenError)
          .addError(ProductPerkServiceError)
          .addError(ProductPerkValidationError)
      )
      .middleware(AuthMiddleware)
      .prefix("/product-perks")
  )
  .add(
    HttpApiGroup.make("sdk")
      .add(
        HttpApiEndpoint.get("getCustomer")`/get-customer`
          .addSuccess(SdkCustomer)
          .setHeaders(SdkHeaders)
          .addError(AuthenticationError)
          .addError(SdkServiceError)
          .addError(SdkCustomerNotFoundError)
          .addError(SdkValidationError)
      )
      .add(
        HttpApiEndpoint.post("identify")`/identify`
          .setPayload(SdkIdentifyBody)
          .addSuccess(SdkCustomer)
          .setHeaders(SdkHeaders)
          .addError(AuthenticationError)
          .addError(SdkServiceError)
          .addError(SdkValidationError)
          .addError(SdkCustomerAlreadyIdentifiedError)
      )
      .add(
        HttpApiEndpoint.post(
          "syncCustomerAttributes"
        )`/sync-customer-attributes`
          .setPayload(SdkSyncCustomerAttributesBody)
          .addSuccess(SdkCustomer)
          .setHeaders(SdkHeaders)
          .addError(AuthenticationError)
          .addError(SdkServiceError)
          .addError(SdkValidationError)
      )
      .add(
        HttpApiEndpoint.post("syncTransaction")`/sync-transaction`
          .setPayload(SdkSyncTransactionBody)
          .addSuccess(SdkSyncTransactionResponse)
          .setHeaders(SdkHeaders)
          .addError(AuthenticationError)
          .addError(SdkServiceError)
          .addError(SdkValidationError)
      )
      .add(
        HttpApiEndpoint.post("evaluateFeatureFlags")`/evaluate-flags`
          .setPayload(EvaluateFeatureFlagsBody)
          .addSuccess(SdkFeatureFlagsResponse)
          .setHeaders(SdkHeaders)
          .addError(AuthenticationError)
          .addError(SdkServiceError)
      )
      .add(
        HttpApiEndpoint.post("resolvePaywall")`/resolve-paywall`
          .setPayload(SdkResolvePaywallBody)
          .addSuccess(Schema.NullOr(SdkResolvedPaywall))
          .setHeaders(SdkHeaders)
          .addError(AuthenticationError)
          .addError(SdkServiceError)
          .addError(SdkValidationError)
      )
      .middleware(AuthMiddleware)
      .prefix("/sdk")
  )
  .add(
    HttpApiGroup.make("users")
      .add(
        HttpApiEndpoint.get("getUser")`/current`
          .addSuccess(User)
          .addError(AuthenticationError)
          .addError(UserServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/users")
  )
  .add(
    HttpApiGroup.make("payment_provider_configurations")
      .add(
        HttpApiEndpoint.get("listPaymentProviderConfigurations")`/`
          .addSuccess(Schema.Array(PaymentProviderConfiguration))
          .addError(ActionForbiddenError)
          .addError(PaymentProviderConfigurationServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/payment-provider-configurations")
  )
  .add(
    HttpApiGroup.make("payment_provider_products")
      .add(
        HttpApiEndpoint.get("listPaymentProviderProducts")`/`
          .addSuccess(Schema.Array(PaymentProviderProduct))
          .addError(ActionForbiddenError)
          .addError(PaymentProviderProductServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/payment-provider-products")
  )
  .add(
    HttpApiGroup.make("changesets")
      .add(
        HttpApiEndpoint.post("deployChangeset")`/deploy`
          .setPayload(DeployChangesetBody)
          .addSuccess(DeployChangesetResponse)
          .addError(AuthenticationError)
          .addError(ActionForbiddenError)
          .addError(ChangesetDeploymentServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/changesets")
  )
  .add(
    HttpApiGroup.make("webhooks")
      .add(
        HttpApiEndpoint.post("createWebhookEndpoint")`/endpoints`
          .setPayload(CreateWebhookEndpointBody)
          .addSuccess(WebhookEndpoint)
          .addError(ActionForbiddenError)
          .addError(WebhookValidationError)
          .addError(WebhookServiceError)
      )
      .add(
        HttpApiEndpoint.get("listWebhookEndpoints")`/endpoints`
          .addSuccess(Schema.Array(WebhookEndpoint))
          .addError(ActionForbiddenError)
          .addError(WebhookServiceError)
      )
      .add(
        HttpApiEndpoint.get("getWebhookEndpoint")`/endpoints/${WebhookEndpointIdParam}`
          .addSuccess(WebhookEndpoint)
          .addError(ActionForbiddenError)
          .addError(WebhookEndpointNotFoundError)
          .addError(WebhookServiceError)
      )
      .add(
        HttpApiEndpoint.patch("updateWebhookEndpoint")`/endpoints/${WebhookEndpointIdParam}`
          .setPayload(UpdateWebhookEndpointBody)
          .addSuccess(WebhookEndpoint)
          .addError(ActionForbiddenError)
          .addError(WebhookEndpointNotFoundError)
          .addError(WebhookValidationError)
          .addError(WebhookServiceError)
      )
      .add(
        HttpApiEndpoint.del("deleteWebhookEndpoint")`/endpoints/${WebhookEndpointIdParam}`
          .addError(ActionForbiddenError)
          .addError(WebhookEndpointNotFoundError)
          .addError(WebhookServiceError)
      )
      .add(
        HttpApiEndpoint.post("rotateWebhookSecret")`/endpoints/${WebhookEndpointIdParam}/rotate-secret`
          .addSuccess(WebhookEndpoint)
          .addError(ActionForbiddenError)
          .addError(WebhookEndpointNotFoundError)
          .addError(WebhookServiceError)
      )
      .add(
        HttpApiEndpoint.post("testWebhookEndpoint")`/endpoints/${WebhookEndpointIdParam}/test`
          .addSuccess(WebhookDelivery)
          .addError(ActionForbiddenError)
          .addError(WebhookEndpointNotFoundError)
          .addError(WebhookServiceError)
      )
      .add(
        HttpApiEndpoint.get("listWebhookDeliveries")`/deliveries`
          .addSuccess(Schema.Array(WebhookDelivery))
          .addError(ActionForbiddenError)
          .addError(WebhookServiceError)
      )
      .add(
        HttpApiEndpoint.get("getWebhookDelivery")`/deliveries/${WebhookDeliveryIdParam}`
          .addSuccess(WebhookDeliveryWithAttempts)
          .addError(ActionForbiddenError)
          .addError(WebhookDeliveryNotFoundError)
          .addError(WebhookServiceError)
      )
      .add(
        HttpApiEndpoint.post("retryWebhookDelivery")`/deliveries/${WebhookDeliveryIdParam}/retry`
          .addSuccess(WebhookDelivery)
          .addError(ActionForbiddenError)
          .addError(WebhookDeliveryNotFoundError)
          .addError(WebhookValidationError)
          .addError(WebhookServiceError)
      )
      .middleware(AuthMiddleware)
      .prefix("/webhooks")
  )

  .prefix("/api/v1");
