"use strict";
// @generated by expo-module-scripts
// oxlint-disable-next-line effect/noDynamicImports -- CommonJS Babel config; Babel loads this file with `require` and reads `module.exports`, so ESM import syntax is not available here.
module.exports = require("expo-module-scripts/babel.config.base");
