/**
 * Generates the checked-in TypeScript lib d.ts asset set the typecheck stage
 * feeds to its fully-virtual CompilerHost.
 *
 * The build's CompilerHost NEVER reads the real filesystem (see `typecheck.ts`),
 * so the standard `lib.*.d.ts` files the installed `typescript` normally loads
 * from its own `lib/` folder have to be embedded as in-memory assets instead.
 * This script resolves the DOM-FREE `lib.es2022.d.ts` reference graph from the
 * installed compiler, follows every transitive `/// <reference lib="…" />`, and
 * writes each file as a string module under `src/lib/`, plus a `src/lib/index.ts`
 * barrel mapping canonical lib file names (`lib.es2022.d.ts`) to their contents.
 *
 * Re-run with `pnpm --filter @voidhash/paywall-build generate:libs` after a
 * TypeScript bump. The output is deterministic and checked in.
 */
import { NodeRuntime, NodeServices } from "@effect/platform-node";
import { Console, Effect, FileSystem, Order, Path, Schema } from "effect";
import ts from "typescript";

/** The DOM-free root lib the build targets (ES2022, no DOM). */
const ROOT_LIB = "lib.es2022.d.ts";
const REFERENCE_RE = /\/\/\/\s*<reference\s+lib=["']([^"']+)["']\s*\/>/g;

/** JSON text for the string literals the generated modules embed. */
const encodeJson = Schema.encodeSync(Schema.UnknownFromJsonString);

/** The canonical file name for a `reference lib="es2022"` target. */
function libFileName(libName: string): string {
  return `lib.${libName}.d.ts`;
}

/** Follow the transitive `/// <reference lib />` graph from the root lib. */
const collectLibs = (tsLibDir: string) =>
  Effect.gen(function* () {
    const fileSystem = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const out = new Map<string, string>();
    const queue = [ROOT_LIB];
    while (queue.length > 0) {
      const fileName = queue.shift()!;
      if (out.has(fileName)) continue;
      const contents = yield* fileSystem.readFileString(path.join(tsLibDir, fileName));
      out.set(fileName, contents);
      for (const match of contents.matchAll(REFERENCE_RE)) {
        queue.push(libFileName(match[1]!));
      }
    }
    return out;
  });

/** A stable identifier for a lib file name, used as its module export name. */
function moduleIdent(fileName: string): string {
  return fileName.replace(/[.-]/g, "_");
}

const program = Effect.gen(function* () {
  const fileSystem = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  // `getDefaultLibFilePath` points at the installed compiler's own `lib/`
  // folder, which is where the `lib.*.d.ts` sources live.
  const tsLibDir = path.dirname(ts.getDefaultLibFilePath({}));
  const here = path.dirname(yield* path.fromFileUrl(new URL(import.meta.url)));
  const outDir = path.join(here, "..", "src", "lib");

  const libs = yield* collectLibs(tsLibDir);
  // Clean regeneration: drop any previously generated *.ts under src/lib.
  // outDir may not exist yet on first run.
  const existing = yield* fileSystem
    .readDirectory(outDir)
    .pipe(Effect.orElseSucceed((): ReadonlyArray<string> => []));
  for (const entry of existing) {
    if (entry.endsWith(".ts")) yield* fileSystem.remove(path.join(outDir, entry));
  }
  yield* fileSystem.makeDirectory(outDir, { recursive: true });

  const sorted = [...libs.entries()].sort(([a], [b]) => Order.String(a, b));
  const barrelLines: string[] = [
    "// AUTO-GENERATED by scripts/generate-libs.ts — do not edit.",
    "// Regenerate with `pnpm --filter @voidhash/paywall-build generate:libs`.",
    "",
  ];
  const entries: string[] = [];
  for (const [fileName, contents] of sorted) {
    const ident = moduleIdent(fileName);
    const moduleFile = `${ident}.ts`;
    yield* fileSystem.writeFileString(
      path.join(outDir, moduleFile),
      `// AUTO-GENERATED by scripts/generate-libs.ts — do not edit.\nexport const ${ident} = ${encodeJson(contents)};\n`,
    );
    barrelLines.push(`import { ${ident} } from "./${ident}.ts";`);
    entries.push(`  ${encodeJson(fileName)}: ${ident},`);
  }
  barrelLines.push("");
  barrelLines.push("/** Canonical lib file name → d.ts contents. */");
  barrelLines.push("export const LIB_ASSETS: Readonly<Record<string, string>> = {");
  barrelLines.push(...entries);
  barrelLines.push("};");
  barrelLines.push("");
  barrelLines.push(`/** The default (root) lib the typecheck stage loads. */`);
  barrelLines.push(`export const DEFAULT_LIB = ${encodeJson(ROOT_LIB)};`);
  barrelLines.push("");

  yield* fileSystem.writeFileString(path.join(outDir, "index.ts"), barrelLines.join("\n"));
  yield* Console.log(`Generated ${sorted.length} lib assets into ${outDir}`);
});

NodeRuntime.runMain(program.pipe(Effect.provide(NodeServices.layer)));
