/**
 * Generates the checked-in TypeScript lib d.ts asset set the typecheck stage
 * feeds to its fully-virtual CompilerHost.
 *
 * The build's CompilerHost NEVER reads the real filesystem (see `typecheck.ts`),
 * so the standard `lib.*.d.ts` files the installed `typescript` normally loads
 * from its own `lib/` folder have to be embedded as in-memory assets instead.
 * This script resolves the DOM-FREE `lib.es2022.d.ts` reference graph from the
 * installed compiler, follows every transitive `/// <reference lib="…" />`, and
 * writes each file as a string module under `src/lib/`, plus a `src/lib/index.ts`
 * barrel mapping canonical lib file names (`lib.es2022.d.ts`) to their contents.
 *
 * Re-run with `pnpm --filter @voidhash/paywall-build generate:libs` after a
 * TypeScript bump. The output is deterministic and checked in.
 */
import { NodeRuntime, NodeServices } from "@effect/platform-node";
import * as Arr from "effect/Array";
import * as Console from "effect/Console";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as HashMap from "effect/HashMap";
import * as Order from "effect/Order";
import * as Path from "effect/Path";
import * as Schema from "effect/Schema";
import ts from "typescript";

/** The DOM-free root lib the build targets (ES2022, no DOM). */
const ROOT_LIB = "lib.es2022.d.ts";
const REFERENCE_RE = /\/\/\/\s*<reference\s+lib=["']([^"']+)["']\s*\/>/g;

/** JSON text for the string literals the generated modules embed. */
const encodeJson = Schema.encodeSync(Schema.UnknownFromJsonString);

/** The canonical file name for a `reference lib="es2022"` target. */
function libFileName(libName: string): string {
  return `lib.${libName}.d.ts`;
}

/** Follow the transitive `/// <reference lib />` graph from the root lib. */
const collectLibs = Effect.fn("collectLibs")(function* (tsLibDir: string) {
  const fileSystem = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  const visit = (
    queue: readonly string[],
    collected: HashMap.HashMap<string, string>,
  ): Effect.Effect<HashMap.HashMap<string, string>, unknown> =>
    Arr.match(queue, {
      onEmpty: () => Effect.succeed(collected),
      onNonEmpty: ([fileName, ...remaining]) => {
        if (HashMap.has(collected, fileName)) return visit(remaining, collected);
        return Effect.gen(function* () {
          const contents = yield* fileSystem.readFileString(path.join(tsLibDir, fileName));
          const references = Array.from(contents.matchAll(REFERENCE_RE)).flatMap((match) =>
            match[1] === undefined ? [] : [libFileName(match[1])],
          );
          return yield* visit(
            [...remaining, ...references],
            HashMap.set(collected, fileName, contents),
          );
        });
      },
    });

  return yield* visit([ROOT_LIB], HashMap.empty());
});

/** A stable identifier for a lib file name, used as its module export name. */
function moduleIdent(fileName: string): string {
  return fileName.replace(/[.-]/g, "_");
}

const program = Effect.fn("generateLibs")(function* () {
  const fileSystem = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  // `getDefaultLibFilePath` points at the installed compiler's own `lib/`
  // folder, which is where the `lib.*.d.ts` sources live.
  const tsLibDir = path.dirname(ts.getDefaultLibFilePath({}));
  const here = path.dirname(yield* path.fromFileUrl(new URL(import.meta.url)));
  const outDir = path.join(here, "..", "src", "lib");

  const libs = yield* collectLibs(tsLibDir);
  // Clean regeneration: drop any previously generated *.ts under src/lib.
  // outDir may not exist yet on first run.
  const existing = yield* fileSystem
    .readDirectory(outDir)
    .pipe(Effect.orElseSucceed((): ReadonlyArray<string> => []));
  yield* Effect.forEach(
    existing.filter((entry) => entry.endsWith(".ts")),
    (entry) => fileSystem.remove(path.join(outDir, entry)),
    { concurrency: "unbounded", discard: true },
  );
  yield* fileSystem.makeDirectory(outDir, { recursive: true });

  const sorted = Arr.sort(
    [...libs],
    Order.mapInput(Order.String, ([fileName]: readonly [string, string]) => fileName),
  );
  const generated = yield* Effect.forEach(
    sorted,
    ([fileName, contents]) => {
      const ident = moduleIdent(fileName);
      const moduleFile = `${ident}.ts`;
      return fileSystem
        .writeFileString(
          path.join(outDir, moduleFile),
          `// AUTO-GENERATED by scripts/generate-libs.ts — do not edit.\nexport const ${ident} = ${encodeJson(contents)};\n`,
        )
        .pipe(
          Effect.as({
            importLine: `import { ${ident} } from "./${ident}.ts";`,
            entryLine: `  ${encodeJson(fileName)}: ${ident},`,
          }),
        );
    },
    { concurrency: 1 },
  );
  const barrelLines = [
    "// AUTO-GENERATED by scripts/generate-libs.ts — do not edit.",
    "// Regenerate with `pnpm --filter @voidhash/paywall-build generate:libs`.",
    "",
    ...generated.map(({ importLine }) => importLine),
    "",
    "/** Canonical lib file name → d.ts contents. */",
    "export const LIB_ASSETS: Readonly<Record<string, string>> = {",
    ...generated.map(({ entryLine }) => entryLine),
    "};",
    "",
    "/** The default (root) lib the typecheck stage loads. */",
    `export const DEFAULT_LIB = ${encodeJson(ROOT_LIB)};`,
    "",
  ];

  yield* fileSystem.writeFileString(path.join(outDir, "index.ts"), barrelLines.join("\n"));
  yield* Console.log(`Generated ${sorted.length} lib assets into ${outDir}`);
})();

NodeRuntime.runMain(program.pipe(Effect.provide(NodeServices.layer)));
