/**
 * Generates the checked-in TypeScript lib d.ts asset set the typecheck stage
 * feeds to its fully-virtual CompilerHost.
 *
 * The build's CompilerHost NEVER reads the real filesystem (see `typecheck.ts`),
 * so the standard `lib.*.d.ts` files the installed `typescript` normally loads
 * from its own `lib/` folder have to be embedded as in-memory assets instead.
 * This script resolves the DOM-FREE `lib.es2022.d.ts` reference graph from the
 * installed compiler, follows every transitive `/// <reference lib="…" />`, and
 * writes each file as a string module under `src/lib/`, plus a `src/lib/index.ts`
 * barrel mapping canonical lib file names (`lib.es2022.d.ts`) to their contents.
 *
 * Re-run with `pnpm --filter @voidhash/paywall-build generate:libs` after a
 * TypeScript bump. The output is deterministic and checked in.
 */
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const tsLibDir = dirname(require.resolve("typescript"));
const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "src", "lib");

/** The DOM-free root lib the build targets (ES2022, no DOM). */
const ROOT_LIB = "lib.es2022.d.ts";
const REFERENCE_RE = /\/\/\/\s*<reference\s+lib=["']([^"']+)["']\s*\/>/g;

/** The canonical file name for a `reference lib="es2022"` target. */
function libFileName(libName: string): string {
  return `lib.${libName}.d.ts`;
}

/** Follow the transitive `/// <reference lib />` graph from the root lib. */
function collectLibs(): Map<string, string> {
  const out = new Map<string, string>();
  const queue = [ROOT_LIB];
  while (queue.length > 0) {
    const fileName = queue.shift()!;
    if (out.has(fileName)) continue;
    const contents = readFileSync(join(tsLibDir, fileName), "utf8");
    out.set(fileName, contents);
    for (const match of contents.matchAll(REFERENCE_RE)) {
      queue.push(libFileName(match[1]!));
    }
  }
  return out;
}

/** A stable identifier for a lib file name, used as its module export name. */
function moduleIdent(fileName: string): string {
  return fileName.replace(/[.-]/g, "_");
}

function main(): void {
  const libs = collectLibs();
  // Clean regeneration: drop any previously generated *.ts under src/lib.
  try {
    for (const entry of readdirSync(outDir)) {
      if (entry.endsWith(".ts")) rmSync(join(outDir, entry));
    }
  } catch {
    // outDir may not exist yet on first run.
  }
  mkdirSync(outDir, { recursive: true });

  const sorted = [...libs.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const barrelLines: string[] = [
    "// AUTO-GENERATED by scripts/generate-libs.ts — do not edit.",
    "// Regenerate with `pnpm --filter @voidhash/paywall-build generate:libs`.",
    "",
  ];
  const entries: string[] = [];
  for (const [fileName, contents] of sorted) {
    const ident = moduleIdent(fileName);
    const moduleFile = `${ident}.ts`;
    writeFileSync(
      join(outDir, moduleFile),
      `// AUTO-GENERATED by scripts/generate-libs.ts — do not edit.\nexport const ${ident} = ${JSON.stringify(contents)};\n`,
    );
    barrelLines.push(`import { ${ident} } from "./${ident}.ts";`);
    entries.push(`  ${JSON.stringify(fileName)}: ${ident},`);
  }
  barrelLines.push("");
  barrelLines.push("/** Canonical lib file name → d.ts contents. */");
  barrelLines.push("export const LIB_ASSETS: Readonly<Record<string, string>> = {");
  barrelLines.push(...entries);
  barrelLines.push("};");
  barrelLines.push("");
  barrelLines.push(`/** The default (root) lib the typecheck stage loads. */`);
  barrelLines.push(`export const DEFAULT_LIB = ${JSON.stringify(ROOT_LIB)};`);
  barrelLines.push("");

  writeFileSync(join(outDir, "index.ts"), barrelLines.join("\n"));
  console.log(`Generated ${sorted.length} lib assets into ${outDir}`);
}

main();
