import Foundation

/// Persisted distinct id used to scope every SDK request.
///
/// Mirrors `src/core/identity/identity-manager.ts`: a missing distinct id lazily becomes an
/// anonymous one, `identify` switches the persisted id, and `reset` clears the whole cache so
/// the next read allocates a fresh anonymous id.
public actor IdentityStore {
    /// Prefix marking a generated, not-yet-identified distinct id.
    public static let anonymousDistinctIdPrefix = "vh:anon:"
    /// Cache key holding the current distinct id.
    public static let cacheKey = "distinctId"

    private let cacheManager: CacheManager
    private let generateAnonymousId: @Sendable () -> String

    /// - Parameters:
    ///   - cacheManager: Cache the distinct id is persisted in.
    ///   - generateAnonymousId: Anonymous id factory, injectable for tests.
    public init(
        cacheManager: CacheManager,
        generateAnonymousId: @escaping @Sendable () -> String = {
            IdentityStore.anonymousDistinctIdPrefix + UUID().uuidString.lowercased()
        }
    ) {
        self.cacheManager = cacheManager
        self.generateAnonymousId = generateAnonymousId
    }

    /// Returns the persisted distinct id, allocating and persisting an anonymous one when absent.
    public func getDistinctId() async -> String {
        if let cached = await getDistinctIdFromCache() {
            return cached
        }

        let anonymousDistinctId = generateAnonymousId()
        await setDistinctId(anonymousDistinctId)
        return anonymousDistinctId
    }

    /// Returns the persisted distinct id without allocating an anonymous one.
    public func getDistinctIdFromCache() async -> String? {
        return await cacheManager.get(IdentityStore.cacheKey, as: String.self)?.value
    }

    /// Persists `distinctId` as the current identity.
    public func identify(distinctId: String) async {
        await setDistinctId(distinctId)
    }

    /// Clears the cache, dropping the persisted identity and every cached response.
    public func reset() async {
        await cacheManager.clear()
    }

    /// Whether `distinctId` was generated by the SDK rather than supplied by the host app.
    public static func isAnonymous(_ distinctId: String) -> Bool {
        return distinctId.hasPrefix(anonymousDistinctIdPrefix)
    }

    private func setDistinctId(_ distinctId: String) async {
        await cacheManager.set(IdentityStore.cacheKey, value: distinctId)
    }
}
