/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedCreateOrgImport } from './routes/_authed/create-org'
import { Route as AuthedIndexImport } from './routes/_authed/~/index'
import { Route as AuthedOrganizationSlugRouteImport } from './routes/_authed/~/$organizationSlug/route'
import { Route as AuthedOrganizationSlugOrganizationsRouteImport } from './routes/_authed/~/$organizationSlug/_organizations/route'
import { Route as AuthedOrganizationSlugProjectSlugRouteImport } from './routes/_authed/~/$organizationSlug/$projectSlug/route'
import { Route as AuthedOrganizationSlugOrganizationsIndexImport } from './routes/_authed/~/$organizationSlug/_organizations/index'
import { Route as AuthedOrganizationSlugOrganizationsProjectsImport } from './routes/_authed/~/$organizationSlug/_organizations/projects'
import { Route as AuthedOrganizationSlugProjectSlugDashboardImport } from './routes/_authed/~/$organizationSlug/$projectSlug/dashboard'
import { Route as AuthedOrganizationSlugOrganizationsSettingsMembersImport } from './routes/_authed/~/$organizationSlug/_organizations/settings/members'
import { Route as AuthedOrganizationSlugOrganizationsSettingsGeneralImport } from './routes/_authed/~/$organizationSlug/_organizations/settings/general'
import { Route as AuthedOrganizationSlugProjectSlugSettingsGeneralImport } from './routes/_authed/~/$organizationSlug/$projectSlug/settings/general'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedCreateOrgRoute = AuthedCreateOrgImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedIndexRoute = AuthedIndexImport.update({
  id: '/~/',
  path: '/~/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedOrganizationSlugRouteRoute =
  AuthedOrganizationSlugRouteImport.update({
    id: '/~/$organizationSlug',
    path: '/~/$organizationSlug',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrganizationSlugOrganizationsRouteRoute =
  AuthedOrganizationSlugOrganizationsRouteImport.update({
    id: '/_organizations',
    getParentRoute: () => AuthedOrganizationSlugRouteRoute,
  } as any)

const AuthedOrganizationSlugProjectSlugRouteRoute =
  AuthedOrganizationSlugProjectSlugRouteImport.update({
    id: '/$projectSlug',
    path: '/$projectSlug',
    getParentRoute: () => AuthedOrganizationSlugRouteRoute,
  } as any)

const AuthedOrganizationSlugOrganizationsIndexRoute =
  AuthedOrganizationSlugOrganizationsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrganizationSlugOrganizationsRouteRoute,
  } as any)

const AuthedOrganizationSlugOrganizationsProjectsRoute =
  AuthedOrganizationSlugOrganizationsProjectsImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthedOrganizationSlugOrganizationsRouteRoute,
  } as any)

const AuthedOrganizationSlugProjectSlugDashboardRoute =
  AuthedOrganizationSlugProjectSlugDashboardImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugRouteRoute,
  } as any)

const AuthedOrganizationSlugOrganizationsSettingsMembersRoute =
  AuthedOrganizationSlugOrganizationsSettingsMembersImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthedOrganizationSlugOrganizationsRouteRoute,
  } as any)

const AuthedOrganizationSlugOrganizationsSettingsGeneralRoute =
  AuthedOrganizationSlugOrganizationsSettingsGeneralImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthedOrganizationSlugOrganizationsRouteRoute,
  } as any)

const AuthedOrganizationSlugProjectSlugSettingsGeneralRoute =
  AuthedOrganizationSlugProjectSlugSettingsGeneralImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/_authed/create-org': {
      id: '/_authed/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof AuthedCreateOrgImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/~/$organizationSlug': {
      id: '/_authed/~/$organizationSlug'
      path: '/~/$organizationSlug'
      fullPath: '/~/$organizationSlug'
      preLoaderRoute: typeof AuthedOrganizationSlugRouteImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/~/': {
      id: '/_authed/~/'
      path: '/~'
      fullPath: '/~'
      preLoaderRoute: typeof AuthedIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/~/$organizationSlug/$projectSlug': {
      id: '/_authed/~/$organizationSlug/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/~/$organizationSlug/$projectSlug'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugRouteImport
      parentRoute: typeof AuthedOrganizationSlugRouteImport
    }
    '/_authed/~/$organizationSlug/_organizations': {
      id: '/_authed/~/$organizationSlug/_organizations'
      path: ''
      fullPath: '/~/$organizationSlug'
      preLoaderRoute: typeof AuthedOrganizationSlugOrganizationsRouteImport
      parentRoute: typeof AuthedOrganizationSlugRouteImport
    }
    '/_authed/~/$organizationSlug/$projectSlug/dashboard': {
      id: '/_authed/~/$organizationSlug/$projectSlug/dashboard'
      path: '/dashboard'
      fullPath: '/~/$organizationSlug/$projectSlug/dashboard'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugDashboardImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugRouteImport
    }
    '/_authed/~/$organizationSlug/_organizations/projects': {
      id: '/_authed/~/$organizationSlug/_organizations/projects'
      path: '/projects'
      fullPath: '/~/$organizationSlug/projects'
      preLoaderRoute: typeof AuthedOrganizationSlugOrganizationsProjectsImport
      parentRoute: typeof AuthedOrganizationSlugOrganizationsRouteImport
    }
    '/_authed/~/$organizationSlug/_organizations/': {
      id: '/_authed/~/$organizationSlug/_organizations/'
      path: '/'
      fullPath: '/~/$organizationSlug/'
      preLoaderRoute: typeof AuthedOrganizationSlugOrganizationsIndexImport
      parentRoute: typeof AuthedOrganizationSlugOrganizationsRouteImport
    }
    '/_authed/~/$organizationSlug/$projectSlug/settings/general': {
      id: '/_authed/~/$organizationSlug/$projectSlug/settings/general'
      path: '/settings/general'
      fullPath: '/~/$organizationSlug/$projectSlug/settings/general'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugSettingsGeneralImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugRouteImport
    }
    '/_authed/~/$organizationSlug/_organizations/settings/general': {
      id: '/_authed/~/$organizationSlug/_organizations/settings/general'
      path: '/settings/general'
      fullPath: '/~/$organizationSlug/settings/general'
      preLoaderRoute: typeof AuthedOrganizationSlugOrganizationsSettingsGeneralImport
      parentRoute: typeof AuthedOrganizationSlugOrganizationsRouteImport
    }
    '/_authed/~/$organizationSlug/_organizations/settings/members': {
      id: '/_authed/~/$organizationSlug/_organizations/settings/members'
      path: '/settings/members'
      fullPath: '/~/$organizationSlug/settings/members'
      preLoaderRoute: typeof AuthedOrganizationSlugOrganizationsSettingsMembersImport
      parentRoute: typeof AuthedOrganizationSlugOrganizationsRouteImport
    }
  }
}

// Create and export the route tree

interface AuthedOrganizationSlugProjectSlugRouteRouteChildren {
  AuthedOrganizationSlugProjectSlugDashboardRoute: typeof AuthedOrganizationSlugProjectSlugDashboardRoute
  AuthedOrganizationSlugProjectSlugSettingsGeneralRoute: typeof AuthedOrganizationSlugProjectSlugSettingsGeneralRoute
}

const AuthedOrganizationSlugProjectSlugRouteRouteChildren: AuthedOrganizationSlugProjectSlugRouteRouteChildren =
  {
    AuthedOrganizationSlugProjectSlugDashboardRoute:
      AuthedOrganizationSlugProjectSlugDashboardRoute,
    AuthedOrganizationSlugProjectSlugSettingsGeneralRoute:
      AuthedOrganizationSlugProjectSlugSettingsGeneralRoute,
  }

const AuthedOrganizationSlugProjectSlugRouteRouteWithChildren =
  AuthedOrganizationSlugProjectSlugRouteRoute._addFileChildren(
    AuthedOrganizationSlugProjectSlugRouteRouteChildren,
  )

interface AuthedOrganizationSlugOrganizationsRouteRouteChildren {
  AuthedOrganizationSlugOrganizationsProjectsRoute: typeof AuthedOrganizationSlugOrganizationsProjectsRoute
  AuthedOrganizationSlugOrganizationsIndexRoute: typeof AuthedOrganizationSlugOrganizationsIndexRoute
  AuthedOrganizationSlugOrganizationsSettingsGeneralRoute: typeof AuthedOrganizationSlugOrganizationsSettingsGeneralRoute
  AuthedOrganizationSlugOrganizationsSettingsMembersRoute: typeof AuthedOrganizationSlugOrganizationsSettingsMembersRoute
}

const AuthedOrganizationSlugOrganizationsRouteRouteChildren: AuthedOrganizationSlugOrganizationsRouteRouteChildren =
  {
    AuthedOrganizationSlugOrganizationsProjectsRoute:
      AuthedOrganizationSlugOrganizationsProjectsRoute,
    AuthedOrganizationSlugOrganizationsIndexRoute:
      AuthedOrganizationSlugOrganizationsIndexRoute,
    AuthedOrganizationSlugOrganizationsSettingsGeneralRoute:
      AuthedOrganizationSlugOrganizationsSettingsGeneralRoute,
    AuthedOrganizationSlugOrganizationsSettingsMembersRoute:
      AuthedOrganizationSlugOrganizationsSettingsMembersRoute,
  }

const AuthedOrganizationSlugOrganizationsRouteRouteWithChildren =
  AuthedOrganizationSlugOrganizationsRouteRoute._addFileChildren(
    AuthedOrganizationSlugOrganizationsRouteRouteChildren,
  )

interface AuthedOrganizationSlugRouteRouteChildren {
  AuthedOrganizationSlugProjectSlugRouteRoute: typeof AuthedOrganizationSlugProjectSlugRouteRouteWithChildren
  AuthedOrganizationSlugOrganizationsRouteRoute: typeof AuthedOrganizationSlugOrganizationsRouteRouteWithChildren
}

const AuthedOrganizationSlugRouteRouteChildren: AuthedOrganizationSlugRouteRouteChildren =
  {
    AuthedOrganizationSlugProjectSlugRouteRoute:
      AuthedOrganizationSlugProjectSlugRouteRouteWithChildren,
    AuthedOrganizationSlugOrganizationsRouteRoute:
      AuthedOrganizationSlugOrganizationsRouteRouteWithChildren,
  }

const AuthedOrganizationSlugRouteRouteWithChildren =
  AuthedOrganizationSlugRouteRoute._addFileChildren(
    AuthedOrganizationSlugRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedCreateOrgRoute: typeof AuthedCreateOrgRoute
  AuthedOrganizationSlugRouteRoute: typeof AuthedOrganizationSlugRouteRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCreateOrgRoute: AuthedCreateOrgRoute,
  AuthedOrganizationSlugRouteRoute:
    AuthedOrganizationSlugRouteRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/create-org': typeof AuthedCreateOrgRoute
  '/~/$organizationSlug': typeof AuthedOrganizationSlugOrganizationsRouteRouteWithChildren
  '/~': typeof AuthedIndexRoute
  '/~/$organizationSlug/$projectSlug': typeof AuthedOrganizationSlugProjectSlugRouteRouteWithChildren
  '/~/$organizationSlug/$projectSlug/dashboard': typeof AuthedOrganizationSlugProjectSlugDashboardRoute
  '/~/$organizationSlug/projects': typeof AuthedOrganizationSlugOrganizationsProjectsRoute
  '/~/$organizationSlug/': typeof AuthedOrganizationSlugOrganizationsIndexRoute
  '/~/$organizationSlug/$projectSlug/settings/general': typeof AuthedOrganizationSlugProjectSlugSettingsGeneralRoute
  '/~/$organizationSlug/settings/general': typeof AuthedOrganizationSlugOrganizationsSettingsGeneralRoute
  '/~/$organizationSlug/settings/members': typeof AuthedOrganizationSlugOrganizationsSettingsMembersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/create-org': typeof AuthedCreateOrgRoute
  '/~/$organizationSlug': typeof AuthedOrganizationSlugOrganizationsIndexRoute
  '/~': typeof AuthedIndexRoute
  '/~/$organizationSlug/$projectSlug': typeof AuthedOrganizationSlugProjectSlugRouteRouteWithChildren
  '/~/$organizationSlug/$projectSlug/dashboard': typeof AuthedOrganizationSlugProjectSlugDashboardRoute
  '/~/$organizationSlug/projects': typeof AuthedOrganizationSlugOrganizationsProjectsRoute
  '/~/$organizationSlug/$projectSlug/settings/general': typeof AuthedOrganizationSlugProjectSlugSettingsGeneralRoute
  '/~/$organizationSlug/settings/general': typeof AuthedOrganizationSlugOrganizationsSettingsGeneralRoute
  '/~/$organizationSlug/settings/members': typeof AuthedOrganizationSlugOrganizationsSettingsMembersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/create-org': typeof AuthedCreateOrgRoute
  '/_authed/~/$organizationSlug': typeof AuthedOrganizationSlugRouteRouteWithChildren
  '/_authed/~/': typeof AuthedIndexRoute
  '/_authed/~/$organizationSlug/$projectSlug': typeof AuthedOrganizationSlugProjectSlugRouteRouteWithChildren
  '/_authed/~/$organizationSlug/_organizations': typeof AuthedOrganizationSlugOrganizationsRouteRouteWithChildren
  '/_authed/~/$organizationSlug/$projectSlug/dashboard': typeof AuthedOrganizationSlugProjectSlugDashboardRoute
  '/_authed/~/$organizationSlug/_organizations/projects': typeof AuthedOrganizationSlugOrganizationsProjectsRoute
  '/_authed/~/$organizationSlug/_organizations/': typeof AuthedOrganizationSlugOrganizationsIndexRoute
  '/_authed/~/$organizationSlug/$projectSlug/settings/general': typeof AuthedOrganizationSlugProjectSlugSettingsGeneralRoute
  '/_authed/~/$organizationSlug/_organizations/settings/general': typeof AuthedOrganizationSlugOrganizationsSettingsGeneralRoute
  '/_authed/~/$organizationSlug/_organizations/settings/members': typeof AuthedOrganizationSlugOrganizationsSettingsMembersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/sign-up'
    | '/create-org'
    | '/~/$organizationSlug'
    | '/~'
    | '/~/$organizationSlug/$projectSlug'
    | '/~/$organizationSlug/$projectSlug/dashboard'
    | '/~/$organizationSlug/projects'
    | '/~/$organizationSlug/'
    | '/~/$organizationSlug/$projectSlug/settings/general'
    | '/~/$organizationSlug/settings/general'
    | '/~/$organizationSlug/settings/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/sign-up'
    | '/create-org'
    | '/~/$organizationSlug'
    | '/~'
    | '/~/$organizationSlug/$projectSlug'
    | '/~/$organizationSlug/$projectSlug/dashboard'
    | '/~/$organizationSlug/projects'
    | '/~/$organizationSlug/$projectSlug/settings/general'
    | '/~/$organizationSlug/settings/general'
    | '/~/$organizationSlug/settings/members'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/sign-up'
    | '/_authed/create-org'
    | '/_authed/~/$organizationSlug'
    | '/_authed/~/'
    | '/_authed/~/$organizationSlug/$projectSlug'
    | '/_authed/~/$organizationSlug/_organizations'
    | '/_authed/~/$organizationSlug/$projectSlug/dashboard'
    | '/_authed/~/$organizationSlug/_organizations/projects'
    | '/_authed/~/$organizationSlug/_organizations/'
    | '/_authed/~/$organizationSlug/$projectSlug/settings/general'
    | '/_authed/~/$organizationSlug/_organizations/settings/general'
    | '/_authed/~/$organizationSlug/_organizations/settings/members'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/create-org",
        "/_authed/~/$organizationSlug",
        "/_authed/~/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/_authed/create-org": {
      "filePath": "_authed/create-org.tsx",
      "parent": "/_authed"
    },
    "/_authed/~/$organizationSlug": {
      "filePath": "_authed/~/$organizationSlug/route.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/~/$organizationSlug/$projectSlug",
        "/_authed/~/$organizationSlug/_organizations"
      ]
    },
    "/_authed/~/": {
      "filePath": "_authed/~/index.ts",
      "parent": "/_authed"
    },
    "/_authed/~/$organizationSlug/$projectSlug": {
      "filePath": "_authed/~/$organizationSlug/$projectSlug/route.tsx",
      "parent": "/_authed/~/$organizationSlug",
      "children": [
        "/_authed/~/$organizationSlug/$projectSlug/dashboard",
        "/_authed/~/$organizationSlug/$projectSlug/settings/general"
      ]
    },
    "/_authed/~/$organizationSlug/_organizations": {
      "filePath": "_authed/~/$organizationSlug/_organizations/route.tsx",
      "parent": "/_authed/~/$organizationSlug",
      "children": [
        "/_authed/~/$organizationSlug/_organizations/projects",
        "/_authed/~/$organizationSlug/_organizations/",
        "/_authed/~/$organizationSlug/_organizations/settings/general",
        "/_authed/~/$organizationSlug/_organizations/settings/members"
      ]
    },
    "/_authed/~/$organizationSlug/$projectSlug/dashboard": {
      "filePath": "_authed/~/$organizationSlug/$projectSlug/dashboard.tsx",
      "parent": "/_authed/~/$organizationSlug/$projectSlug"
    },
    "/_authed/~/$organizationSlug/_organizations/projects": {
      "filePath": "_authed/~/$organizationSlug/_organizations/projects.tsx",
      "parent": "/_authed/~/$organizationSlug/_organizations"
    },
    "/_authed/~/$organizationSlug/_organizations/": {
      "filePath": "_authed/~/$organizationSlug/_organizations/index.tsx",
      "parent": "/_authed/~/$organizationSlug/_organizations"
    },
    "/_authed/~/$organizationSlug/$projectSlug/settings/general": {
      "filePath": "_authed/~/$organizationSlug/$projectSlug/settings/general.tsx",
      "parent": "/_authed/~/$organizationSlug/$projectSlug"
    },
    "/_authed/~/$organizationSlug/_organizations/settings/general": {
      "filePath": "_authed/~/$organizationSlug/_organizations/settings/general.tsx",
      "parent": "/_authed/~/$organizationSlug/_organizations"
    },
    "/_authed/~/$organizationSlug/_organizations/settings/members": {
      "filePath": "_authed/~/$organizationSlug/_organizations/settings/members.tsx",
      "parent": "/_authed/~/$organizationSlug/_organizations"
    }
  }
}
ROUTE_MANIFEST_END */
