/**
 * `@voidhash/paywalls/schema` — the shared wire-format contract for paywall
 * deploys: the §2 component manifest, §3 preview node tree, §3.1 style subset
 * types, their version constants, and **dependency-free** runtime validators.
 *
 * This entry pulls in NO `react` and NO `effect`, so it is safe to import from
 * a build tool, a server trust boundary, or a browser sandbox alike. The
 * voidhash server's effect-Schema decoders mirror these validators exactly and
 * a contract test locks the two together.
 */
export {
  COMPONENT_MANIFEST_VERSION,
  type ComponentManifest,
  type ManifestAction,
  type ManifestActionPayloadKind,
  type ManifestArrayItem,
  type ManifestArrayProp,
  type ManifestBooleanProp,
  type ManifestComponentProp,
  type ManifestHostData,
  type ManifestImageProp,
  type ManifestNumberProp,
  type ManifestProp,
  type ManifestPropEditor,
  type ManifestPropKind,
  type ManifestRefProp,
  type ManifestRefType,
  type ManifestSelectProp,
  type ManifestStringProp,
} from "./component-manifest";
export {
  PAYWALL_TREE_VERSION,
  type PaywallImageNode,
  type PaywallNode,
  type PaywallNodeResizeMode,
  type PaywallNodeTree,
  type PaywallPlaceholderNode,
  type PaywallPressableNode,
  type PaywallScrollNode,
  type PaywallSlotNode,
  type PaywallTextNode,
  type PaywallViewNode,
} from "./node-tree";
export {
  type ActionEditorFieldNode,
  type AlignmentGridNode,
  type ButtonNode,
  type CalloutNode,
  type ColorFieldNode,
  type ColorPickerNode,
  type ColumnNode,
  type DefaultPropsNode,
  type DimensionFieldNode,
  type FieldNode,
  type FillFieldNode,
  type GradientStopsNode,
  type IconName,
  type ImageFieldNode,
  type MenuNode,
  PANEL_CAPS,
  PANEL_ICON_NAME_LIST,
  PANEL_NODE_SPECS,
  PANEL_TREE_VERSION,
  type PanelJsonValue,
  type PanelNode,
  type PanelNodeBase,
  type PanelNodeSpec,
  type PanelNodeType,
  type PanelRootNode,
  type PanelTree,
  type PopoverContentNode,
  type PopoverNode,
  type PopoverTriggerNode,
  type ProductFieldNode,
  type PropFieldNode,
  type ResetAffordanceNode,
  type RowNode,
  type SectionActionsNode,
  type SectionNode,
  type SelectFieldNode,
  type SliderFieldNode,
  type SubsectionNode,
  type SwatchNode,
  type SwitchFieldNode,
  type TextFieldNode,
  type TextNode,
  type ToggleGroupNode,
  type VariableFieldNode,
} from "./panel-tree";
export {
  PAYWALL_STYLE_KEY_LIST,
  type PaywallAlignItems,
  type PaywallAlignSelf,
  type PaywallBackgroundGradient,
  type PaywallBackgroundImage,
  type PaywallBackgroundType,
  type PaywallDimension,
  type PaywallFlexDirection,
  type PaywallFontWeight,
  type PaywallGradientStop,
  type PaywallJustifyContent,
  type PaywallStyle,
  type StyleProp,
} from "./style";
export {
  countSlotNodes,
  DEPLOY_SLUG_PATTERN,
  PAYWALL_STYLE_KEYS,
  type ParseResult,
  parseComponentManifest,
  parsePreviewTree,
  PREVIEW_STATE_PATTERN,
} from "./validate";
export {
  PANEL_ICON_NAMES,
  type ParsePanelResult,
  parsePanelTree,
} from "./validate-panel";
