// voidhash.gen.d.ts — generated by voidhash-cli, do not edit
// @voidhash:version sha256:e6f6dbac538ef9956b435013a314f220ac028d21762b4777096a0b1df7966a13
// @voidhash:fetched-at 2026-05-11T14:56:24.982Z

declare module "@voidhash/react-native" {
  interface VoidhashRegister {
    schema: {
      products: never;
      locations: never;
      perks: "test" | "test-2";
    };
  }
}

export {};
