// voidhash.gen.d.ts — generated by voidhash-cli, do not edit
// @voidhash:version sha256:3f90ef2a787d32c6dfe6a60ffe6e9aed5dfc614bc6e26d0d433cc64b9a0acbc5
// @voidhash:fetched-at 2026-06-30T08:36:31.608Z

declare module "@voidhash/react-native" {
  interface VoidhashRegister {
    schema: {
      products: never;
      locations: never;
      perks: never;
    };
  }
}

export {};
