// voidhash.gen.d.ts — generated by voidhash-cli, do not edit
// @voidhash:version sha256:placeholder
// @voidhash:fetched-at 1970-01-01T00:00:00.000Z

declare module "@voidhash/react-native" {
  interface VoidhashRegister {
    schema: {
      products: never;
      locations: never;
      perks: never;
    };
  }
}

export {};
