// Core abstractions for defining nodes and properties
export {
  buildUpdateObject,
  type CanvasDef,
  createNodeData,
  defineCanvas,
  defineNode,
  defineProperty,
  getNodeDef,
  getUpdatableProperties,
  isCanvasDef,
  isNodeDef,
  isPropertyDef,
  type NodeDef,
  type NodeDefData,
  type NodeDefType,
  type ParentRef,
  ParentRefSchema,
  type PropertyDef,
  type PropertyDefName,
  type PropertyDefType,
  pickDefined
} from './core';

// Document exports
export {
  createDesignDocument,
  DesignDocument,
  deleteNode,
  deleteNodeSync,
  encodeNode,
  fromYDoc,
  getAllNodes,
  getAllNodesSync,
  getNode,
  getNodeSync,
  getRootNode,
  NodeNotFoundError,
  NodeParseError,
  parseNode,
  setColumnNodeSync,
  setNode,
  setNodeSync,
  setRootNode,
  setRootNodeSync,
  setRowNodeSync,
  setScreenNodeSync,
  setTextNodeSync,
  updateColumnNodeSync,
  updateNodeParentSync,
  updateNodeProperties,
  updateRowNodeSync,
  updateScreenNodeSync,
  updateTextNodeSync
} from './document';

// Schema exports (nodes, properties, canvas)
export {
  type AlignItems,
  AlignItemsSchema,
  alignItems,
  backgroundColor,
  backgroundColorNullable,
  type ColumnNodeData,
  ColumnNodeSchema,
  color,
  columnNode,
  DEFAULT_PADDING,
  DEFAULT_SAFE_AREA,
  designCanvas,
  type FontWeight,
  FontWeightSchema,
  fontSize,
  fontWeight,
  gap,
  hasParent,
  height,
  isRootNode,
  type JustifyContent,
  JustifyContentSchema,
  justifyContent,
  letterSpacing,
  lineHeight,
  type NodeData,
  type NodeDataWithoutRoot,
  NodeSchema,
  type Padding,
  PaddingSchema,
  paddingBottom,
  paddingLeft,
  paddingProperties,
  paddingRight,
  paddingTop,
  type RootNodeData,
  RootNodeSchema,
  type RowNodeData,
  RowNodeSchema,
  rowNode,
  type SafeArea,
  SafeAreaSchema,
  type ScreenNodeData,
  ScreenNodeSchema,
  safeAreaBottom,
  safeAreaProperties,
  safeAreaTop,
  screenNode,
  type TextAlign,
  TextAlignSchema,
  type TextNodeData,
  TextNodeSchema,
  text,
  textAlign,
  textNode,
  width,
  x,
  y
} from './schema';
