icon: Component
title: Components
pages:
  - overview
  - accordion
  - alert
  - alert-dialog
  - avatar
  - badge
  - breadcrumb
  - button
  - calendar
  - card
  - carousel
  - chart
  - checkbox
  - collapsible
  - command
  - context-menu
  - dialog
  - drawer
  - dropdown-menu
  - dropzone
  - form
  - hover-card
  - input
  - input-otp
  - label
  - menubar
  - navigation-menu
  - page-bar
  - pagination
  - popover
  - progress
  - radio-group
  - resizable
  - scroll-area
  - select
  - separator
  - sheet
  - sidebar
  - skeleton
  - slider
  - sonner
  - switch
  - table
  - tabs
  - textarea
  - toggle
  - toggle-group
  - tooltip
  - underline-tabs
