// Package eventcaptureapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package eventcaptureapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CaptureDependencyUnavailableErrorTag.
const (
	CaptureDependencyUnavailableErrorTagCaptureDependencyUnavailableError CaptureDependencyUnavailableErrorTag = "CaptureDependencyUnavailableError"
)

// Defines values for CaptureDependencyUnavailableErrorCode.
const (
	DependencyUnavailable CaptureDependencyUnavailableErrorCode = "dependency_unavailable"
)

// Defines values for CaptureInternalServerErrorTag.
const (
	CaptureInternalServerErrorTagCaptureInternalServerError CaptureInternalServerErrorTag = "CaptureInternalServerError"
)

// Defines values for CaptureInternalServerErrorCode.
const (
	InternalError CaptureInternalServerErrorCode = "internal_error"
)

// Defines values for CaptureInvalidRequestErrorTag.
const (
	CaptureInvalidRequestErrorTagCaptureInvalidRequestError CaptureInvalidRequestErrorTag = "CaptureInvalidRequestError"
)

// Defines values for CaptureInvalidRequestErrorCode.
const (
	InvalidRequest CaptureInvalidRequestErrorCode = "invalid_request"
)

// Defines values for CapturePayloadTooLargeErrorTag.
const (
	CapturePayloadTooLargeErrorTagCapturePayloadTooLargeError CapturePayloadTooLargeErrorTag = "CapturePayloadTooLargeError"
)

// Defines values for CapturePayloadTooLargeErrorCode.
const (
	PayloadTooLarge CapturePayloadTooLargeErrorCode = "payload_too_large"
)

// Defines values for CaptureRateLimitedErrorTag.
const (
	CaptureRateLimitedErrorTagCaptureRateLimitedError CaptureRateLimitedErrorTag = "CaptureRateLimitedError"
)

// Defines values for CaptureRateLimitedErrorCode.
const (
	RateLimited CaptureRateLimitedErrorCode = "rate_limited"
)

// Defines values for CaptureUnauthorizedErrorTag.
const (
	CaptureUnauthorizedErrorTagCaptureUnauthorizedError CaptureUnauthorizedErrorTag = "CaptureUnauthorizedError"
)

// Defines values for CaptureUnauthorizedErrorCode.
const (
	Unauthorized CaptureUnauthorizedErrorCode = "unauthorized"
)

// CaptureAcceptedResponse defines model for CaptureAcceptedResponse.
type CaptureAcceptedResponse struct {
	Accepted int `json:"accepted"`
	Rejected int `json:"rejected"`
}

// CaptureContextValue defines model for CaptureContextValue.
type CaptureContextValue struct {
	union json.RawMessage
}

// CaptureContextValue0 defines model for .
type CaptureContextValue0 = string

// CaptureContextValue1 defines model for .
type CaptureContextValue1 = float32

// CaptureContextValue2 defines model for .
type CaptureContextValue2 = bool

// CaptureContextValue3 defines model for .
type CaptureContextValue3 = []CaptureContextValue

// CaptureContextValue4 defines model for .
type CaptureContextValue4 map[string]*CaptureContextValue

// CaptureDependencyUnavailableError defines model for CaptureDependencyUnavailableError.
type CaptureDependencyUnavailableError struct {
	UnderscoreTag CaptureDependencyUnavailableErrorTag  `json:"_tag"`
	Code          CaptureDependencyUnavailableErrorCode `json:"code"`
	Error         string                                `json:"error"`
}

// CaptureDependencyUnavailableErrorTag defines model for CaptureDependencyUnavailableError.Tag.
type CaptureDependencyUnavailableErrorTag string

// CaptureDependencyUnavailableErrorCode defines model for CaptureDependencyUnavailableError.Code.
type CaptureDependencyUnavailableErrorCode string

// CaptureEventValue defines model for CaptureEventValue.
type CaptureEventValue struct {
	union json.RawMessage
}

// CaptureEventValue0 defines model for .
type CaptureEventValue0 = string

// CaptureEventValue1 defines model for .
type CaptureEventValue1 = float32

// CaptureEventValue2 defines model for .
type CaptureEventValue2 = bool

// CaptureEventValue3 defines model for .
type CaptureEventValue3 = []CaptureEventValue

// CaptureEventValue4 defines model for .
type CaptureEventValue4 map[string]*CaptureEventValue

// CaptureInternalServerError defines model for CaptureInternalServerError.
type CaptureInternalServerError struct {
	UnderscoreTag CaptureInternalServerErrorTag  `json:"_tag"`
	Code          CaptureInternalServerErrorCode `json:"code"`
	Error         string                         `json:"error"`
}

// CaptureInternalServerErrorTag defines model for CaptureInternalServerError.Tag.
type CaptureInternalServerErrorTag string

// CaptureInternalServerErrorCode defines model for CaptureInternalServerError.Code.
type CaptureInternalServerErrorCode string

// CaptureInvalidRequestError defines model for CaptureInvalidRequestError.
type CaptureInvalidRequestError struct {
	UnderscoreTag CaptureInvalidRequestErrorTag  `json:"_tag"`
	Code          CaptureInvalidRequestErrorCode `json:"code"`
	Error         string                         `json:"error"`
}

// CaptureInvalidRequestErrorTag defines model for CaptureInvalidRequestError.Tag.
type CaptureInvalidRequestErrorTag string

// CaptureInvalidRequestErrorCode defines model for CaptureInvalidRequestError.Code.
type CaptureInvalidRequestErrorCode string

// CapturePayloadTooLargeError defines model for CapturePayloadTooLargeError.
type CapturePayloadTooLargeError struct {
	UnderscoreTag CapturePayloadTooLargeErrorTag  `json:"_tag"`
	Code          CapturePayloadTooLargeErrorCode `json:"code"`
	Error         string                          `json:"error"`
}

// CapturePayloadTooLargeErrorTag defines model for CapturePayloadTooLargeError.Tag.
type CapturePayloadTooLargeErrorTag string

// CapturePayloadTooLargeErrorCode defines model for CapturePayloadTooLargeError.Code.
type CapturePayloadTooLargeErrorCode string

// CaptureRateLimitedError defines model for CaptureRateLimitedError.
type CaptureRateLimitedError struct {
	UnderscoreTag CaptureRateLimitedErrorTag  `json:"_tag"`
	Code          CaptureRateLimitedErrorCode `json:"code"`
	Error         string                      `json:"error"`
	RetryAfterMs  *int                        `json:"retry_after_ms"`
}

// CaptureRateLimitedErrorTag defines model for CaptureRateLimitedError.Tag.
type CaptureRateLimitedErrorTag string

// CaptureRateLimitedErrorCode defines model for CaptureRateLimitedError.Code.
type CaptureRateLimitedErrorCode string

// CaptureUnauthorizedError defines model for CaptureUnauthorizedError.
type CaptureUnauthorizedError struct {
	UnderscoreTag CaptureUnauthorizedErrorTag  `json:"_tag"`
	Code          CaptureUnauthorizedErrorCode `json:"code"`
	Error         string                       `json:"error"`
}

// CaptureUnauthorizedErrorTag defines model for CaptureUnauthorizedError.Tag.
type CaptureUnauthorizedErrorTag string

// CaptureUnauthorizedErrorCode defines model for CaptureUnauthorizedError.Code.
type CaptureUnauthorizedErrorCode string

// EventCaptureBatchJSONBody defines parameters for EventCaptureBatch.
type EventCaptureBatchJSONBody struct {
	Events []struct {
		Context    map[string]*CaptureEventValue   `json:"context"`
		DistinctId string                          `json:"distinct_id"`
		Event      string                          `json:"event"`
		Properties map[string]*CaptureContextValue `json:"properties"`
		SessionId  *string                         `json:"session_id"`
		Timestamp  string                          `json:"timestamp"`
		Uuid       string                          `json:"uuid"`
	} `json:"events"`
	SentAt string  `json:"sent_at"`
	Token  *string `json:"token"`
}

// EventCaptureBatchParams defines parameters for EventCaptureBatch.
type EventCaptureBatchParams struct {
	XSecretKey *string `json:"x-secret-key,omitempty"`
}

// EventCaptureCaptureJSONBody defines parameters for EventCaptureCapture.
type EventCaptureCaptureJSONBody struct {
	Context    map[string]*CaptureEventValue   `json:"context"`
	DistinctId string                          `json:"distinct_id"`
	Event      string                          `json:"event"`
	Properties map[string]*CaptureContextValue `json:"properties"`
	SentAt     string                          `json:"sent_at"`
	SessionId  *string                         `json:"session_id"`
	Timestamp  string                          `json:"timestamp"`
	Token      *string                         `json:"token"`
	Uuid       string                          `json:"uuid"`
}

// EventCaptureCaptureParams defines parameters for EventCaptureCapture.
type EventCaptureCaptureParams struct {
	XSecretKey *string `json:"x-secret-key,omitempty"`
}

// EventCaptureBatchJSONRequestBody defines body for EventCaptureBatch for application/json ContentType.
type EventCaptureBatchJSONRequestBody EventCaptureBatchJSONBody

// EventCaptureCaptureJSONRequestBody defines body for EventCaptureCapture for application/json ContentType.
type EventCaptureCaptureJSONRequestBody EventCaptureCaptureJSONBody

// AsCaptureContextValue0 returns the union data inside the CaptureContextValue as a CaptureContextValue0
func (t CaptureContextValue) AsCaptureContextValue0() (CaptureContextValue0, error) {
	var body CaptureContextValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureContextValue0 overwrites any union data inside the CaptureContextValue as the provided CaptureContextValue0
func (t *CaptureContextValue) FromCaptureContextValue0(v CaptureContextValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureContextValue0 performs a merge with any union data inside the CaptureContextValue, using the provided CaptureContextValue0
func (t *CaptureContextValue) MergeCaptureContextValue0(v CaptureContextValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCaptureContextValue1 returns the union data inside the CaptureContextValue as a CaptureContextValue1
func (t CaptureContextValue) AsCaptureContextValue1() (CaptureContextValue1, error) {
	var body CaptureContextValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureContextValue1 overwrites any union data inside the CaptureContextValue as the provided CaptureContextValue1
func (t *CaptureContextValue) FromCaptureContextValue1(v CaptureContextValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureContextValue1 performs a merge with any union data inside the CaptureContextValue, using the provided CaptureContextValue1
func (t *CaptureContextValue) MergeCaptureContextValue1(v CaptureContextValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCaptureContextValue2 returns the union data inside the CaptureContextValue as a CaptureContextValue2
func (t CaptureContextValue) AsCaptureContextValue2() (CaptureContextValue2, error) {
	var body CaptureContextValue2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureContextValue2 overwrites any union data inside the CaptureContextValue as the provided CaptureContextValue2
func (t *CaptureContextValue) FromCaptureContextValue2(v CaptureContextValue2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureContextValue2 performs a merge with any union data inside the CaptureContextValue, using the provided CaptureContextValue2
func (t *CaptureContextValue) MergeCaptureContextValue2(v CaptureContextValue2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCaptureContextValue3 returns the union data inside the CaptureContextValue as a CaptureContextValue3
func (t CaptureContextValue) AsCaptureContextValue3() (CaptureContextValue3, error) {
	var body CaptureContextValue3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureContextValue3 overwrites any union data inside the CaptureContextValue as the provided CaptureContextValue3
func (t *CaptureContextValue) FromCaptureContextValue3(v CaptureContextValue3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureContextValue3 performs a merge with any union data inside the CaptureContextValue, using the provided CaptureContextValue3
func (t *CaptureContextValue) MergeCaptureContextValue3(v CaptureContextValue3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCaptureContextValue4 returns the union data inside the CaptureContextValue as a CaptureContextValue4
func (t CaptureContextValue) AsCaptureContextValue4() (CaptureContextValue4, error) {
	var body CaptureContextValue4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureContextValue4 overwrites any union data inside the CaptureContextValue as the provided CaptureContextValue4
func (t *CaptureContextValue) FromCaptureContextValue4(v CaptureContextValue4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureContextValue4 performs a merge with any union data inside the CaptureContextValue, using the provided CaptureContextValue4
func (t *CaptureContextValue) MergeCaptureContextValue4(v CaptureContextValue4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CaptureContextValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CaptureContextValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCaptureEventValue0 returns the union data inside the CaptureEventValue as a CaptureEventValue0
func (t CaptureEventValue) AsCaptureEventValue0() (CaptureEventValue0, error) {
	var body CaptureEventValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureEventValue0 overwrites any union data inside the CaptureEventValue as the provided CaptureEventValue0
func (t *CaptureEventValue) FromCaptureEventValue0(v CaptureEventValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureEventValue0 performs a merge with any union data inside the CaptureEventValue, using the provided CaptureEventValue0
func (t *CaptureEventValue) MergeCaptureEventValue0(v CaptureEventValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCaptureEventValue1 returns the union data inside the CaptureEventValue as a CaptureEventValue1
func (t CaptureEventValue) AsCaptureEventValue1() (CaptureEventValue1, error) {
	var body CaptureEventValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureEventValue1 overwrites any union data inside the CaptureEventValue as the provided CaptureEventValue1
func (t *CaptureEventValue) FromCaptureEventValue1(v CaptureEventValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureEventValue1 performs a merge with any union data inside the CaptureEventValue, using the provided CaptureEventValue1
func (t *CaptureEventValue) MergeCaptureEventValue1(v CaptureEventValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCaptureEventValue2 returns the union data inside the CaptureEventValue as a CaptureEventValue2
func (t CaptureEventValue) AsCaptureEventValue2() (CaptureEventValue2, error) {
	var body CaptureEventValue2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureEventValue2 overwrites any union data inside the CaptureEventValue as the provided CaptureEventValue2
func (t *CaptureEventValue) FromCaptureEventValue2(v CaptureEventValue2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureEventValue2 performs a merge with any union data inside the CaptureEventValue, using the provided CaptureEventValue2
func (t *CaptureEventValue) MergeCaptureEventValue2(v CaptureEventValue2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCaptureEventValue3 returns the union data inside the CaptureEventValue as a CaptureEventValue3
func (t CaptureEventValue) AsCaptureEventValue3() (CaptureEventValue3, error) {
	var body CaptureEventValue3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureEventValue3 overwrites any union data inside the CaptureEventValue as the provided CaptureEventValue3
func (t *CaptureEventValue) FromCaptureEventValue3(v CaptureEventValue3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureEventValue3 performs a merge with any union data inside the CaptureEventValue, using the provided CaptureEventValue3
func (t *CaptureEventValue) MergeCaptureEventValue3(v CaptureEventValue3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCaptureEventValue4 returns the union data inside the CaptureEventValue as a CaptureEventValue4
func (t CaptureEventValue) AsCaptureEventValue4() (CaptureEventValue4, error) {
	var body CaptureEventValue4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCaptureEventValue4 overwrites any union data inside the CaptureEventValue as the provided CaptureEventValue4
func (t *CaptureEventValue) FromCaptureEventValue4(v CaptureEventValue4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCaptureEventValue4 performs a merge with any union data inside the CaptureEventValue, using the provided CaptureEventValue4
func (t *CaptureEventValue) MergeCaptureEventValue4(v CaptureEventValue4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CaptureEventValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CaptureEventValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// EventCaptureBatchWithBody request with any body
	EventCaptureBatchWithBody(ctx context.Context, params *EventCaptureBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EventCaptureBatch(ctx context.Context, params *EventCaptureBatchParams, body EventCaptureBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EventCaptureCaptureWithBody request with any body
	EventCaptureCaptureWithBody(ctx context.Context, params *EventCaptureCaptureParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EventCaptureCapture(ctx context.Context, params *EventCaptureCaptureParams, body EventCaptureCaptureJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) EventCaptureBatchWithBody(ctx context.Context, params *EventCaptureBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEventCaptureBatchRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EventCaptureBatch(ctx context.Context, params *EventCaptureBatchParams, body EventCaptureBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEventCaptureBatchRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EventCaptureCaptureWithBody(ctx context.Context, params *EventCaptureCaptureParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEventCaptureCaptureRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EventCaptureCapture(ctx context.Context, params *EventCaptureCaptureParams, body EventCaptureCaptureJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEventCaptureCaptureRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewEventCaptureBatchRequest calls the generic EventCaptureBatch builder with application/json body
func NewEventCaptureBatchRequest(server string, params *EventCaptureBatchParams, body EventCaptureBatchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEventCaptureBatchRequestWithBody(server, params, "application/json", bodyReader)
}

// NewEventCaptureBatchRequestWithBody generates requests for EventCaptureBatch with any type of body
func NewEventCaptureBatchRequestWithBody(server string, params *EventCaptureBatchParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/i/v1/batch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XSecretKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-secret-key", runtime.ParamLocationHeader, *params.XSecretKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-secret-key", headerParam0)
		}

	}

	return req, nil
}

// NewEventCaptureCaptureRequest calls the generic EventCaptureCapture builder with application/json body
func NewEventCaptureCaptureRequest(server string, params *EventCaptureCaptureParams, body EventCaptureCaptureJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEventCaptureCaptureRequestWithBody(server, params, "application/json", bodyReader)
}

// NewEventCaptureCaptureRequestWithBody generates requests for EventCaptureCapture with any type of body
func NewEventCaptureCaptureRequestWithBody(server string, params *EventCaptureCaptureParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/i/v1/capture")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XSecretKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-secret-key", runtime.ParamLocationHeader, *params.XSecretKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-secret-key", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// EventCaptureBatchWithBodyWithResponse request with any body
	EventCaptureBatchWithBodyWithResponse(ctx context.Context, params *EventCaptureBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EventCaptureBatchResponse, error)

	EventCaptureBatchWithResponse(ctx context.Context, params *EventCaptureBatchParams, body EventCaptureBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*EventCaptureBatchResponse, error)

	// EventCaptureCaptureWithBodyWithResponse request with any body
	EventCaptureCaptureWithBodyWithResponse(ctx context.Context, params *EventCaptureCaptureParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EventCaptureCaptureResponse, error)

	EventCaptureCaptureWithResponse(ctx context.Context, params *EventCaptureCaptureParams, body EventCaptureCaptureJSONRequestBody, reqEditors ...RequestEditorFn) (*EventCaptureCaptureResponse, error)
}

type EventCaptureBatchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *CaptureAcceptedResponse
	JSON400      *CaptureInvalidRequestError
	JSON401      *CaptureUnauthorizedError
	JSON413      *CapturePayloadTooLargeError
	JSON429      *CaptureRateLimitedError
	JSON500      *CaptureInternalServerError
	JSON503      *CaptureDependencyUnavailableError
}

// Status returns HTTPResponse.Status
func (r EventCaptureBatchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EventCaptureBatchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EventCaptureCaptureResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *CaptureAcceptedResponse
	JSON400      *CaptureInvalidRequestError
	JSON401      *CaptureUnauthorizedError
	JSON413      *CapturePayloadTooLargeError
	JSON429      *CaptureRateLimitedError
	JSON500      *CaptureInternalServerError
	JSON503      *CaptureDependencyUnavailableError
}

// Status returns HTTPResponse.Status
func (r EventCaptureCaptureResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EventCaptureCaptureResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// EventCaptureBatchWithBodyWithResponse request with arbitrary body returning *EventCaptureBatchResponse
func (c *ClientWithResponses) EventCaptureBatchWithBodyWithResponse(ctx context.Context, params *EventCaptureBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EventCaptureBatchResponse, error) {
	rsp, err := c.EventCaptureBatchWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEventCaptureBatchResponse(rsp)
}

func (c *ClientWithResponses) EventCaptureBatchWithResponse(ctx context.Context, params *EventCaptureBatchParams, body EventCaptureBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*EventCaptureBatchResponse, error) {
	rsp, err := c.EventCaptureBatch(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEventCaptureBatchResponse(rsp)
}

// EventCaptureCaptureWithBodyWithResponse request with arbitrary body returning *EventCaptureCaptureResponse
func (c *ClientWithResponses) EventCaptureCaptureWithBodyWithResponse(ctx context.Context, params *EventCaptureCaptureParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EventCaptureCaptureResponse, error) {
	rsp, err := c.EventCaptureCaptureWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEventCaptureCaptureResponse(rsp)
}

func (c *ClientWithResponses) EventCaptureCaptureWithResponse(ctx context.Context, params *EventCaptureCaptureParams, body EventCaptureCaptureJSONRequestBody, reqEditors ...RequestEditorFn) (*EventCaptureCaptureResponse, error) {
	rsp, err := c.EventCaptureCapture(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEventCaptureCaptureResponse(rsp)
}

// ParseEventCaptureBatchResponse parses an HTTP response from a EventCaptureBatchWithResponse call
func ParseEventCaptureBatchResponse(rsp *http.Response) (*EventCaptureBatchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EventCaptureBatchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest CaptureAcceptedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CaptureInvalidRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CaptureUnauthorizedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest CapturePayloadTooLargeError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest CaptureRateLimitedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest CaptureInternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest CaptureDependencyUnavailableError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseEventCaptureCaptureResponse parses an HTTP response from a EventCaptureCaptureWithResponse call
func ParseEventCaptureCaptureResponse(rsp *http.Response) (*EventCaptureCaptureResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EventCaptureCaptureResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest CaptureAcceptedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CaptureInvalidRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CaptureUnauthorizedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest CapturePayloadTooLargeError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest CaptureRateLimitedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest CaptureInternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest CaptureDependencyUnavailableError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
