/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/_dashboard/route'
import { Route as AuthenticatedCreateOrganizationIndexRouteImport } from './routes/_authenticated/create-organization/index'
import { Route as AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteImport } from './routes/_authenticated/_dashboard/_organization/$organizationSlug/route'
import { Route as AuthenticatedDashboardOrganizationOrganizationSlugIndexRouteImport } from './routes/_authenticated/_dashboard/_organization/$organizationSlug/index'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/route'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/index'
import { Route as AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRouteImport } from './routes/_authenticated/_designer/$organizationSlug.$projectSlug.design.$id'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products.index'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/paywalls.index'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers.index'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers.index'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/general'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products.$id'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers.perks'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers.api-keys'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers.$id'
import { Route as AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRouteImport } from './routes/_authenticated/_dashboard/_organization/$organizationSlug/~/settings.general'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers.index'
import { Route as AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRouteImport } from './routes/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers.$paymentProviderConfigurationId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreateOrganizationIndexRoute =
  AuthenticatedCreateOrganizationIndexRouteImport.update({
    id: '/create-organization/',
    path: '/create-organization/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardOrganizationOrganizationSlugRouteRoute =
  AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteImport.update({
    id: '/_organization/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardOrganizationOrganizationSlugIndexRoute =
  AuthenticatedDashboardOrganizationOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedDashboardOrganizationOrganizationSlugRouteRoute,
  } as any)
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteImport.update(
    {
      id: '/_project/$organizationSlug/$projectSlug',
      path: '/$organizationSlug/$projectSlug',
      getParentRoute: () => AuthenticatedDashboardRouteRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )
const AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRoute =
  AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRouteImport.update({
    id: '/_designer/$organizationSlug/$projectSlug/design/$id',
    path: '/$organizationSlug/$projectSlug/design/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteImport.update(
    {
      id: '/developers',
      path: '/developers',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRouteImport.update(
    {
      id: '/products/',
      path: '/products/',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRouteImport.update(
    {
      id: '/paywalls/',
      path: '/paywalls/',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRouteImport.update(
    {
      id: '/customers/',
      path: '/customers/',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRouteImport.update(
    {
      id: '/settings/general',
      path: '/settings/general',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRouteImport.update(
    {
      id: '/products/$id',
      path: '/products/$id',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRouteImport.update(
    {
      id: '/perks',
      path: '/perks',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRouteImport.update(
    {
      id: '/api-keys',
      path: '/api-keys',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRouteImport.update(
    {
      id: '/customers/$id',
      path: '/customers/$id',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )
const AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRoute =
  AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRouteImport.update(
    {
      id: '/~/settings/general',
      path: '/~/settings/general',
      getParentRoute: () =>
        AuthenticatedDashboardOrganizationOrganizationSlugRouteRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRouteImport.update(
    {
      id: '/settings/payment-providers/',
      path: '/settings/payment-providers/',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )
const AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRoute =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRouteImport.update(
    {
      id: '/settings/payment-providers/$paymentProviderConfigurationId',
      path: '/settings/payment-providers/$paymentProviderConfigurationId',
      getParentRoute: () =>
        AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/create-organization': typeof AuthenticatedCreateOrganizationIndexRoute
  '/$organizationSlug': typeof AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteWithChildren
  '/$organizationSlug/$projectSlug': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteWithChildren
  '/$organizationSlug/': typeof AuthenticatedDashboardOrganizationOrganizationSlugIndexRoute
  '/$organizationSlug/$projectSlug/developers': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteWithChildren
  '/$organizationSlug/$projectSlug/design/$id': typeof AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRoute
  '/$organizationSlug/$projectSlug/': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRoute
  '/$organizationSlug/~/settings/general': typeof AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRoute
  '/$organizationSlug/$projectSlug/customers/$id': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRoute
  '/$organizationSlug/$projectSlug/developers/api-keys': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRoute
  '/$organizationSlug/$projectSlug/developers/perks': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRoute
  '/$organizationSlug/$projectSlug/products/$id': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRoute
  '/$organizationSlug/$projectSlug/settings/general': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRoute
  '/$organizationSlug/$projectSlug/customers': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRoute
  '/$organizationSlug/$projectSlug/developers/': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRoute
  '/$organizationSlug/$projectSlug/paywalls': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRoute
  '/$organizationSlug/$projectSlug/products': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRoute
  '/$organizationSlug/$projectSlug/settings/payment-providers/$paymentProviderConfigurationId': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRoute
  '/$organizationSlug/$projectSlug/settings/payment-providers': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/create-organization': typeof AuthenticatedCreateOrganizationIndexRoute
  '/$organizationSlug': typeof AuthenticatedDashboardOrganizationOrganizationSlugIndexRoute
  '/$organizationSlug/$projectSlug/design/$id': typeof AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRoute
  '/$organizationSlug/$projectSlug': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRoute
  '/$organizationSlug/~/settings/general': typeof AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRoute
  '/$organizationSlug/$projectSlug/customers/$id': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRoute
  '/$organizationSlug/$projectSlug/developers/api-keys': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRoute
  '/$organizationSlug/$projectSlug/developers/perks': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRoute
  '/$organizationSlug/$projectSlug/products/$id': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRoute
  '/$organizationSlug/$projectSlug/settings/general': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRoute
  '/$organizationSlug/$projectSlug/customers': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRoute
  '/$organizationSlug/$projectSlug/developers': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRoute
  '/$organizationSlug/$projectSlug/paywalls': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRoute
  '/$organizationSlug/$projectSlug/products': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRoute
  '/$organizationSlug/$projectSlug/settings/payment-providers/$paymentProviderConfigurationId': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRoute
  '/$organizationSlug/$projectSlug/settings/payment-providers': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/create-organization/': typeof AuthenticatedCreateOrganizationIndexRoute
  '/_authenticated/_dashboard/_organization/$organizationSlug': typeof AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteWithChildren
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteWithChildren
  '/_authenticated/_dashboard/_organization/$organizationSlug/': typeof AuthenticatedDashboardOrganizationOrganizationSlugIndexRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteWithChildren
  '/_authenticated/_designer/$organizationSlug/$projectSlug/design/$id': typeof AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRoute
  '/_authenticated/_dashboard/_organization/$organizationSlug/~/settings/general': typeof AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers/$id': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/api-keys': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/perks': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products/$id': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/general': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers/': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/paywalls/': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products/': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers/$paymentProviderConfigurationId': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRoute
  '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers/': typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization'
    | '/$organizationSlug'
    | '/$organizationSlug/$projectSlug'
    | '/$organizationSlug/'
    | '/$organizationSlug/$projectSlug/developers'
    | '/$organizationSlug/$projectSlug/design/$id'
    | '/$organizationSlug/$projectSlug/'
    | '/$organizationSlug/~/settings/general'
    | '/$organizationSlug/$projectSlug/customers/$id'
    | '/$organizationSlug/$projectSlug/developers/api-keys'
    | '/$organizationSlug/$projectSlug/developers/perks'
    | '/$organizationSlug/$projectSlug/products/$id'
    | '/$organizationSlug/$projectSlug/settings/general'
    | '/$organizationSlug/$projectSlug/customers'
    | '/$organizationSlug/$projectSlug/developers/'
    | '/$organizationSlug/$projectSlug/paywalls'
    | '/$organizationSlug/$projectSlug/products'
    | '/$organizationSlug/$projectSlug/settings/payment-providers/$paymentProviderConfigurationId'
    | '/$organizationSlug/$projectSlug/settings/payment-providers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/$organizationSlug'
    | '/$organizationSlug/$projectSlug/design/$id'
    | '/$organizationSlug/$projectSlug'
    | '/$organizationSlug/~/settings/general'
    | '/$organizationSlug/$projectSlug/customers/$id'
    | '/$organizationSlug/$projectSlug/developers/api-keys'
    | '/$organizationSlug/$projectSlug/developers/perks'
    | '/$organizationSlug/$projectSlug/products/$id'
    | '/$organizationSlug/$projectSlug/settings/general'
    | '/$organizationSlug/$projectSlug/customers'
    | '/$organizationSlug/$projectSlug/developers'
    | '/$organizationSlug/$projectSlug/paywalls'
    | '/$organizationSlug/$projectSlug/products'
    | '/$organizationSlug/$projectSlug/settings/payment-providers/$paymentProviderConfigurationId'
    | '/$organizationSlug/$projectSlug/settings/payment-providers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_dashboard'
    | '/_authenticated/'
    | '/_authenticated/create-organization/'
    | '/_authenticated/_dashboard/_organization/$organizationSlug'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug'
    | '/_authenticated/_dashboard/_organization/$organizationSlug/'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers'
    | '/_authenticated/_designer/$organizationSlug/$projectSlug/design/$id'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/'
    | '/_authenticated/_dashboard/_organization/$organizationSlug/~/settings/general'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers/$id'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/api-keys'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/perks'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products/$id'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/general'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers/'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/paywalls/'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products/'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers/$paymentProviderConfigurationId'
    | '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-organization/': {
      id: '/_authenticated/create-organization/'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof AuthenticatedCreateOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_dashboard/_organization/$organizationSlug': {
      id: '/_authenticated/_dashboard/_organization/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/_dashboard/_organization/$organizationSlug/': {
      id: '/_authenticated/_dashboard/_organization/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationOrganizationSlugIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardOrganizationOrganizationSlugRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug'
      path: '/$organizationSlug/$projectSlug'
      fullPath: '/$organizationSlug/$projectSlug'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/'
      path: '/'
      fullPath: '/$organizationSlug/$projectSlug/'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
    '/_authenticated/_designer/$organizationSlug/$projectSlug/design/$id': {
      id: '/_authenticated/_designer/$organizationSlug/$projectSlug/design/$id'
      path: '/$organizationSlug/$projectSlug/design/$id'
      fullPath: '/$organizationSlug/$projectSlug/design/$id'
      preLoaderRoute: typeof AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers'
      path: '/developers'
      fullPath: '/$organizationSlug/$projectSlug/developers'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products/': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products/'
      path: '/products'
      fullPath: '/$organizationSlug/$projectSlug/products'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/paywalls/': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/paywalls/'
      path: '/paywalls'
      fullPath: '/$organizationSlug/$projectSlug/paywalls'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/'
      path: '/'
      fullPath: '/$organizationSlug/$projectSlug/developers/'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers/': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers/'
      path: '/customers'
      fullPath: '/$organizationSlug/$projectSlug/customers'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/general': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/general'
      path: '/settings/general'
      fullPath: '/$organizationSlug/$projectSlug/settings/general'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products/$id': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/products/$id'
      path: '/products/$id'
      fullPath: '/$organizationSlug/$projectSlug/products/$id'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/perks': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/perks'
      path: '/perks'
      fullPath: '/$organizationSlug/$projectSlug/developers/perks'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/api-keys': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/developers/api-keys'
      path: '/api-keys'
      fullPath: '/$organizationSlug/$projectSlug/developers/api-keys'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers/$id': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/customers/$id'
      path: '/customers/$id'
      fullPath: '/$organizationSlug/$projectSlug/customers/$id'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
    '/_authenticated/_dashboard/_organization/$organizationSlug/~/settings/general': {
      id: '/_authenticated/_dashboard/_organization/$organizationSlug/~/settings/general'
      path: '/~/settings/general'
      fullPath: '/$organizationSlug/~/settings/general'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedDashboardOrganizationOrganizationSlugRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers/': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers/'
      path: '/settings/payment-providers'
      fullPath: '/$organizationSlug/$projectSlug/settings/payment-providers'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
    '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers/$paymentProviderConfigurationId': {
      id: '/_authenticated/_dashboard/_project/$organizationSlug/$projectSlug/settings/payment-providers/$paymentProviderConfigurationId'
      path: '/settings/payment-providers/$paymentProviderConfigurationId'
      fullPath: '/$organizationSlug/$projectSlug/settings/payment-providers/$paymentProviderConfigurationId'
      preLoaderRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRouteImport
      parentRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute
    }
  }
}

interface AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteChildren {
  AuthenticatedDashboardOrganizationOrganizationSlugIndexRoute: typeof AuthenticatedDashboardOrganizationOrganizationSlugIndexRoute
  AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRoute: typeof AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRoute
}

const AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteChildren: AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteChildren =
  {
    AuthenticatedDashboardOrganizationOrganizationSlugIndexRoute:
      AuthenticatedDashboardOrganizationOrganizationSlugIndexRoute,
    AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRoute:
      AuthenticatedDashboardOrganizationOrganizationSlugChar126SettingsGeneralRoute,
  }

const AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteWithChildren =
  AuthenticatedDashboardOrganizationOrganizationSlugRouteRoute._addFileChildren(
    AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteChildren,
  )

interface AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteChildren {
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRoute
}

const AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteChildren: AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteChildren =
  {
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersApiKeysRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersPerksRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersIndexRoute,
  }

const AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteWithChildren =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute._addFileChildren(
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteChildren,
  )

interface AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteChildren {
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteWithChildren
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRoute
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRoute
}

const AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteChildren: AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteChildren =
  {
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugDevelopersRouteWithChildren,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugIndexRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIdRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIdRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsGeneralRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugCustomersIndexRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugPaywallsIndexRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugProductsIndexRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersPaymentProviderConfigurationIdRoute,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugSettingsPaymentProvidersIndexRoute,
  }

const AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteWithChildren =
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute._addFileChildren(
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardOrganizationOrganizationSlugRouteRoute: typeof AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteWithChildren
  AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute: typeof AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteWithChildren
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardOrganizationOrganizationSlugRouteRoute:
      AuthenticatedDashboardOrganizationOrganizationSlugRouteRouteWithChildren,
    AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRoute:
      AuthenticatedDashboardProjectOrganizationSlugProjectSlugRouteRouteWithChildren,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCreateOrganizationIndexRoute: typeof AuthenticatedCreateOrganizationIndexRoute
  AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRoute: typeof AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCreateOrganizationIndexRoute:
    AuthenticatedCreateOrganizationIndexRoute,
  AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRoute:
    AuthenticatedDesignerOrganizationSlugProjectSlugDesignIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
