import * as esbuild from "esbuild";
import { readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as tsup from "tsup";

const rootDir = path.dirname(fileURLToPath(import.meta.url));
const distDir = path.join(rootDir, "dist");

/** IIFE global the sandbox bundle assigns its exports to (keep in sync with `src/sandbox`). */
const SANDBOX_GLOBAL_NAME = "__VOIDHASH_PAYWALLS_SANDBOX__";

/**
 * Builds every published entry with tsup (types + cjs/esm). The `sandbox` and
 * `monaco-surface` entries keep react/react-reconciler external like the rest;
 * the browser IIFE that bundles them IN is produced separately below.
 */
const buildEntries = async (): Promise<void> => {
  await tsup.build({
    dts: true,
    entryPoints: {
      // Composition grammar/AST/printer/dts + inert author surface. Mimic-free;
      // imports `typescript` (external) for the whitelist parser.
      compose: "./src/compose/index.ts",
      dom: "./src/dom.tsx",
      index: "./src/index.ts",
      "jsx-dev-runtime": "./src/jsx-dev-runtime.ts",
      "jsx-runtime": "./src/jsx-runtime.ts",
      panel: "./src/panel/index.ts",
      // Node-importable sandbox surface (renderComponentToTree etc.); the
      // browser IIFE is bundled separately.
      sandbox: "./src/sandbox/index.tsx",
      // Dependency-free wire-format entry: nothing here imports react, so it
      // stays out of the shared chunk and carries no react at runtime.
      schema: "./src/schema/index.ts",
      tree: "./src/tree.ts",
    },
    external: [
      "react",
      "react-dom",
      "react/jsx-runtime",
      "react/jsx-dev-runtime",
      // Node-only dependency of the `tree`/`sandbox` entries; never reaches the
      // browser entries because nothing outside `src/tree-renderer` imports it.
      "react-reconciler",
      "react-reconciler/constants",
      // The composition parser imports the TypeScript compiler; keep it external
      // (consumers provide it as an optional peer) instead of inlining ~10MB.
      "typescript",
    ],
    format: ["cjs", "esm"],
    outDir: "./dist",
    outExtension: (ctx) => {
      if (ctx.format === "cjs") {
        // `.cjs` because package.json declares `"type": "module"` — a plain
        // `.js` would be loaded as ESM by Node and break the require path.
        return { dts: ".d.ts", js: ".cjs" };
      }
      return { dts: ".d.mts", js: ".mjs" };
    },
    sourcemap: true,
    // Split shared code (runtime, primitives, contexts) into common chunks all
    // entries import. Without this, each entry would inline its own copy of
    // the runtime — yielding distinct React contexts, so e.g. a component
    // rendered by `@voidhash/paywalls/tree` could not resolve the tree host
    // installed through `RendererProvider`. Splitting guarantees a single
    // shared instance.
    splitting: true,
    target: "es2022",
    esbuildOptions: (options) => {
      options.jsx = "automatic";
    },
  });
};

/**
 * Bundles `src/sandbox/index.tsx` into a self-contained browser IIFE with
 * react + react-reconciler bundled IN, assigning its exports to
 * {@link SANDBOX_GLOBAL_NAME}. The studio evals this once inside its sandbox
 * iframe. Minified, production react (dev-only warnings/checks dropped), no
 * network — everything the compiled component needs comes from this global.
 */
const buildSandboxIife = async (): Promise<string> => {
  const result = await esbuild.build({
    bundle: true,
    define: { "process.env.NODE_ENV": '"production"' },
    entryPoints: [path.join(rootDir, "src/sandbox/index.tsx")],
    // esbuild emits `"use strict"; var <name> = (…)()`. Under a strict-mode
    // indirect `eval` (the sandbox path) a top-level `var` does NOT attach to
    // the global object, so we explicitly assign the global in a footer that
    // runs in the same scope.
    footer: {
      js: `if(typeof globalThis!=="undefined"){globalThis.${SANDBOX_GLOBAL_NAME}=${SANDBOX_GLOBAL_NAME};}`,
    },
    format: "iife",
    globalName: SANDBOX_GLOBAL_NAME,
    jsx: "automatic",
    minify: true,
    platform: "browser",
    sourcemap: false,
    target: "es2022",
    treeShaking: true,
    write: false,
  });
  if (result.errors.length > 0) {
    throw new Error(`sandbox IIFE build failed:\n${JSON.stringify(result.errors, null, 2)}`);
  }
  const bundle = result.outputFiles[0]!.text;
  writeFileSync(path.join(distDir, "sandbox.global.js"), bundle);
  return bundle;
};

/**
 * Emits `dist/sandbox-bundle.{mjs,cjs,d.ts}` — a node-importable module
 * exporting the sandbox IIFE bundle text. Mirrors how the retired
 * `paywall-sdk/host` shipped its runtime string, so the studio can pass it into
 * the iframe without a separate asset fetch.
 */
const writeSandboxBundleModule = (bundle: string): void => {
  const banner = "// AUTO-GENERATED by build.ts — the sandbox IIFE bundle text. Do not edit.\n";
  const globalDecl = `export const SANDBOX_GLOBAL_NAME = ${JSON.stringify(SANDBOX_GLOBAL_NAME)};\n`;
  const bundleDecl = `export const sandboxRuntimeBundle = ${JSON.stringify(bundle)};\n`;
  writeFileSync(path.join(distDir, "sandbox-bundle.mjs"), banner + globalDecl + bundleDecl);
  writeFileSync(
    path.join(distDir, "sandbox-bundle.cjs"),
    `${banner}"use strict";\nObject.defineProperty(exports, "__esModule", { value: true });\nexports.SANDBOX_GLOBAL_NAME = ${JSON.stringify(SANDBOX_GLOBAL_NAME)};\nexports.sandboxRuntimeBundle = ${JSON.stringify(bundle)};\n`,
  );
  writeFileSync(
    path.join(distDir, "sandbox-bundle.d.ts"),
    "export declare const SANDBOX_GLOBAL_NAME: string;\nexport declare const sandboxRuntimeBundle: string;\n",
  );
};

/**
 * Bundles one author-surface entry into ONE self-contained `.d.ts` (a dedicated
 * `splitting: false` dts build inlines every referenced chunk into a single
 * file, unlike the shared-chunk main build). Emitted into `dist/monaco/` and
 * returned as text for {@link toAmbientModuleBody}.
 */
const buildSelfContainedDts = async (name: string, entry: string): Promise<string> => {
  const outDir = path.join(distDir, "monaco");
  await tsup.build({
    dts: { only: true },
    entryPoints: { [name]: entry },
    external: ["react", "react-dom", "react/jsx-runtime", "react/jsx-dev-runtime"],
    format: ["esm"],
    outDir,
    // No shared chunks: force rollup-dts to inline all referenced types into a
    // single self-contained declaration file we can wrap in a module.
    splitting: false,
    target: "es2022",
  });
  const dts = readFileSync(path.join(outDir, `${name}.d.ts`), "utf8");
  // The single-file dts is a build intermediate — don't ship it in the package.
  rmSync(outDir, { force: true, recursive: true });
  return dts;
};

// Minimal React type stub prepended to each ambient module body — authors only
// need the paywall surface to type-check; react internals are intentionally
// opaque. Shared by every `@voidhash/paywalls*` ambient block.
const REACT_STUB = [
  "  // Minimal React type stubs — authors only need the paywall surface to",
  "  // type-check; react internals are intentionally opaque here.",
  "  type ReactNode = any;",
  "  type CSSProperties = Record<string, string | number>;",
  "  type ReactProvider<T> = (props: { value: T; children?: ReactNode }) => ReactNode;",
  "  export function useState<S>(initial: S | (() => S)): [S, (next: S | ((prev: S) => S)) => void];",
  "  export function useEffect(effect: () => void | (() => void), deps?: readonly unknown[]): void;",
  "  export function useMemo<T>(factory: () => T, deps?: readonly unknown[]): T;",
  "  export function useCallback<T>(callback: T, deps?: readonly unknown[]): T;",
  "  export function useRef<T>(initial: T): { current: T };",
].join("\n");

// Names the react stub supplies; drop any duplicate re-export of them so an
// ambient module has a single definition per identifier.
const STUBBED_HOOKS = new Set(["useState", "useEffect", "useMemo", "useCallback", "useRef"]);

/**
 * Turns a self-contained declaration file into the BODY of a `declare module`
 * ambient block: drops the `react` imports/re-exports (the {@link REACT_STUB}
 * supplies the hooks and `ReactNode`/`CSSProperties`), strips `export` on nested
 * `declare` statements (illegal inside an ambient module body), rewrites the few
 * `react.*` qualified references onto the local stubs, and re-indents.
 */
const toAmbientModuleBody = (raw: string): string =>
  raw
    .split("\n")
    .filter((line) => {
      const trimmed = line.trim();
      // Drop every react import/re-export — the stubs above supply the hooks
      // and ReactNode/CSSProperties; everything else is inlined already.
      if (/\bfrom\s+["']react(\/[^"']+)?["'];?$/.test(trimmed)) {
        return false;
      }
      return true;
    })
    // `declare` is illegal inside an already-ambient module body; strip it.
    .map((line) => line.replace(/^(\s*)declare\s+/, "$1"))
    // Neutralize `react.*` qualified references the inlined chunks may still
    // carry (e.g. `react.ReactNode`), pointing them at the local stubs.
    .map((line) =>
      line
        .replace(/\breact\.ReactNode\b/g, "ReactNode")
        .replace(/\breact\.CSSProperties\b/g, "CSSProperties")
        .replace(/\breact\.Provider\b/g, "ReactProvider"),
    )
    // Drop bare re-export lines that only re-export the stubbed hook names
    // (leaves the local `export {…}` block that re-exports the real surface).
    .filter((line) => {
      const match = line.match(/^export\s*\{([^}]*)\}\s*;?\s*$/);
      if (!match) {
        return true;
      }
      const names = match[1]!.split(",").map((n) =>
        n
          .trim()
          .split(/\s+as\s+/)[0]!
          .trim(),
      );
      return !names.every((name) => STUBBED_HOOKS.has(name));
    })
    .map((line) => (line.length > 0 ? `  ${line}` : line))
    .join("\n");

/**
 * Assembles the `sandboxDts` string Monaco loads via `addExtraLib`: the
 * `@voidhash/paywalls` ambient module (component authoring), the
 * `@voidhash/paywalls/panel` ambient module (editor-panel authoring), and the
 * jsx-runtime shim — each self-contained.
 */
const writeSandboxDtsModule = (surfaceRaw: string, panelRaw: string): void => {
  const surfaceBody = toAmbientModuleBody(surfaceRaw);
  const panelBody = toAmbientModuleBody(panelRaw);

  const dts = [
    `declare module "@voidhash/paywalls" {\n${REACT_STUB}\n\n${surfaceBody}\n}`,
    `declare module "@voidhash/paywalls/panel" {\n${REACT_STUB}\n\n${panelBody}\n}`,
    `declare module "@voidhash/paywalls/jsx-runtime" {\n  export const Fragment: unknown;\n  export function jsx(type: unknown, props: unknown, key?: unknown): unknown;\n  export function jsxs(type: unknown, props: unknown, key?: unknown): unknown;\n}`,
  ].join("\n\n") + "\n";

  const banner = "// AUTO-GENERATED by build.ts from the real .d.ts — do not edit.\n";
  writeFileSync(
    path.join(distDir, "sandbox-dts.mjs"),
    `${banner}export const sandboxDts = ${JSON.stringify(dts)};\n`,
  );
  writeFileSync(
    path.join(distDir, "sandbox-dts.cjs"),
    `${banner}"use strict";\nObject.defineProperty(exports, "__esModule", { value: true });\nexports.sandboxDts = ${JSON.stringify(dts)};\n`,
  );
  writeFileSync(
    path.join(distDir, "sandbox-dts.d.ts"),
    "export declare const sandboxDts: string;\n",
  );
};

const main = async (): Promise<void> => {
  await buildEntries();
  const bundle = await buildSandboxIife();
  writeSandboxBundleModule(bundle);
  const surfaceDts = await buildSelfContainedDts(
    "monaco-surface",
    "./src/sandbox/monaco-surface.ts",
  );
  const panelDts = await buildSelfContainedDts("panel-surface", "./src/panel/monaco-surface.ts");
  writeSandboxDtsModule(surfaceDts, panelDts);
};

main().catch((error) => {
  // biome-ignore lint/suspicious/noConsole: Build script should print the failure.
  console.error(error);
  process.exit(1);
});
